import {
  getTenseLessonById,
  tenseLessons,
  type LessonQuestion,
} from "@/features/tenses/lesson-data"

type ChoiceSeed = readonly [lessonId: string, label: string]

interface MixedQuestionSeed {
  id: string
  lessonId: string
  context: string
  before: string
  after: string
  whyCorrect: string
  contrast: string
  choices: readonly ChoiceSeed[]
}

const mixedQuestionSeeds: MixedQuestionSeed[] = [
  {
    id: "present-simple-01",
    lessonId: "present-simple",
    context: "渡轮时刻表贴在码头入口，工作人员正在提醒等候的乘客。",
    before: "The last ferry to the island ",
    after: " at 8:40 on Saturdays.",
    whyCorrect: "这是固定时刻表上的出发安排，一般现在时常用于班次和日程。",
    contrast: "句子说明的是每周重复的班次，不是眼前的一次动作",
    choices: [
      ["present-simple", "leaves"],
      ["present-continuous", "is leaving"],
      ["past-simple", "left"],
      ["future-simple", "will leave"],
    ],
  },
  {
    id: "present-simple-02",
    lessonId: "present-simple",
    context: "摄影师比较两台相机在暗处的表现，描述其中一台的常见特点。",
    before: "In low light, this camera ",
    after: " more slowly than the other model.",
    whyCorrect: "句子陈述相机稳定的性能特点，属于一般事实。",
    contrast: "比较的是相机一贯的性能，不是某次正在发生的对焦过程",
    choices: [
      ["present-simple", "focuses"],
      ["present-continuous", "is focusing"],
      ["present-perfect", "has focused"],
      ["past-simple", "focused"],
    ],
  },
  {
    id: "present-simple-03",
    lessonId: "present-simple",
    context: "花店老板介绍 Mina 每天开店前的工作习惯。",
    before: "Mina ",
    after: " the greenhouse before the shop opens.",
    whyCorrect: "开店前检查温室是 Mina 反复进行的日常安排。",
    contrast: "这是长期重复的工作习惯，而不是这一次暂时进行的动作",
    choices: [
      ["present-simple", "checks"],
      ["present-continuous", "is checking"],
      ["past-simple", "checked"],
      ["present-perfect-continuous", "has been checking"],
    ],
  },
  {
    id: "present-simple-04",
    lessonId: "present-simple",
    context: "列车显示屏正在核对当天各站的固定停靠信息。",
    before: "The 10:15 train ",
    after: " at platform 2.",
    whyCorrect: "列车固定班次使用一般现在时描述。",
    contrast: "显示屏列出的是时刻表安排，不是列车此刻正在停靠",
    choices: [
      ["present-simple", "stops"],
      ["present-continuous", "is stopping"],
      ["past-simple", "stopped"],
      ["future-perfect", "will have stopped"],
    ],
  },
  {
    id: "present-simple-05",
    lessonId: "present-simple",
    context: "厨师解释配方为什么能让酥皮保持酥脆。",
    before: "This recipe ",
    after: " olive oil instead of butter.",
    whyCorrect: "配方的固定组成用一般现在时表达。",
    contrast: "句子说明配方长期不变的内容，不是在报告一次使用经历",
    choices: [
      ["present-simple", "uses"],
      ["present-continuous", "is using"],
      ["past-simple", "used"],
      ["present-perfect", "has used"],
    ],
  },
  {
    id: "present-continuous-01",
    lessonId: "present-continuous",
    context: "歌手还在试音，音响师正根据现场声音调整设备。",
    before: "The sound engineer ",
    after: " the microphone levels while the singer rehearses.",
    whyCorrect: "调整和排练在当前这个现场同时进行，动作尚未结束。",
    contrast: "描述的是眼前正在进行的现场工作，不是日常职责或已完成的调整",
    choices: [
      ["present-continuous", "is adjusting"],
      ["present-simple", "adjusts"],
      ["past-simple", "adjusted"],
      ["present-perfect", "has adjusted"],
    ],
  },
  {
    id: "present-continuous-02",
    lessonId: "present-continuous",
    context: "主阅览厅维修期间，图书馆临时把一间会议室开放给备考学生。",
    before: "For this month, the library ",
    after: " a quiet room for exam candidates.",
    whyCorrect: "for this month 表示这段时间内的临时安排，适合现在进行时。",
    contrast: "图书馆只是本月暂时这样安排，不是永久服务，也不是过去的一次使用",
    choices: [
      ["present-continuous", "is using"],
      ["present-simple", "uses"],
      ["past-simple", "used"],
      ["future-simple", "will use"],
    ],
  },
  {
    id: "present-continuous-03",
    lessonId: "present-continuous",
    context: "日历上已经确认了接站安排，对方昨天刚发来抵达时间。",
    before: "We ",
    after: " Dr. Shah at the station tomorrow morning.",
    whyCorrect: "已经确认的近期个人安排可以用现在进行时表达将来。",
    contrast: "这是已经落实到日历的个人约定，不是临时预测或固定公共时刻表",
    choices: [
      ["present-continuous", "are meeting"],
      ["present-simple", "meet"],
      ["future-simple", "will meet"],
      ["past-simple", "met"],
    ],
  },
  {
    id: "present-continuous-04",
    lessonId: "present-continuous",
    context: "观察染料变化，蓝色区域在布料变干的过程中越来越深。",
    before: "The blue patch ",
    after: " darker as the fabric dries.",
    whyCorrect: "颜色正在逐渐变化，句子突出当前持续发生的过程。",
    contrast: "描述的是眼下逐渐变化的过程，而不是一般规律或已经完成的结果",
    choices: [
      ["present-continuous", "is getting"],
      ["present-simple", "gets"],
      ["past-simple", "got"],
      ["present-perfect", "has become"],
    ],
  },
  {
    id: "present-continuous-05",
    lessonId: "present-continuous",
    context: "Omar 平时远程办公，但这周团队把他安排到市中心办公室。",
    before: "Although he usually works remotely, this week Omar ",
    after: " from the downtown office.",
    whyCorrect: "this week 标出一个暂时阶段；usually 也衬出它和长期习惯不同。",
    contrast: "题目特意说明这只是本周的临时状态，不是他的稳定工作习惯",
    choices: [
      ["present-continuous", "is working"],
      ["present-simple", "works"],
      ["present-perfect", "has worked"],
      ["past-simple", "worked"],
    ],
  },
  {
    id: "present-perfect-01",
    lessonId: "present-perfect",
    context: "海岸调查还在继续，队员汇报目前已经标记的巢穴数量。",
    before: "The team ",
    after: " three coastal nests so far.",
    whyCorrect: "so far 把已经完成的数量连到尚未结束的调查阶段。",
    contrast: "调查阶段仍在继续，汇报的是截至现在的累计成果",
    choices: [
      ["present-perfect", "has located"],
      ["past-simple", "located"],
      ["present-continuous", "is locating"],
      ["past-perfect", "had located"],
    ],
  },
  {
    id: "present-perfect-02",
    lessonId: "present-perfect",
    context: "我现在打不开柜子，大家正在找那把黄铜钥匙。",
    before: "Someone ",
    after: " the brass key, so I can't open the cabinet.",
    whyCorrect: "钥匙不见了这一结果直接影响现在，适合现在完成时。",
    contrast: "句子强调钥匙现在不在原处造成的结果，没有交代已结束的过去时间",
    choices: [
      ["present-perfect", "has taken"],
      ["past-simple", "took"],
      ["present-simple", "takes"],
      ["past-perfect", "had taken"],
    ],
  },
  {
    id: "present-perfect-03",
    lessonId: "present-perfect",
    context: "西班牙语小说中的习语对 Sofia 来说都很陌生。",
    before: "Sofia ",
    after: " a novel in Spanish before.",
    whyCorrect: "before 在这里询问截至现在的人生经历，不指某个已结束时点。",
    contrast: "题目问的是她到现在为止有没有这种经历，而非某次具体的过去阅读",
    choices: [
      ["present-perfect", "has never read"],
      ["past-simple", "never read"],
      ["past-perfect", "had never read"],
      ["present-continuous", "is never reading"],
    ],
  },
  {
    id: "present-perfect-04",
    lessonId: "present-perfect",
    context: "今天上午的检查还没结束，负责人汇报目前已完成的安全工作；新实验室下午开放。",
    before: "So far this morning, our department ",
    after: " its safety checklist, so staff can use the new lab.",
    whyCorrect: "so far this morning 把已完成的工作放在尚未结束的时间段内，且结果与实验室开放有关。",
    contrast: "今天上午还没结束，句子汇报截至现在已完成的清单更新",
    choices: [
      ["present-perfect", "has updated"],
      ["past-simple", "updated"],
      ["present-continuous", "is updating"],
      ["future-perfect", "will have updated"],
    ],
  },
  {
    id: "present-perfect-05",
    lessonId: "present-perfect",
    context: "清点还没结束，Nora 报告目前已经复核的箱子。",
    before: "Nora ",
    after: " twenty boxes, but the count is still in progress.",
    whyCorrect: "复核数量是截至目前的阶段性成果，工作还未结束。",
    contrast: "现在仍在清点，句子汇报当前累计完成量而不是某次过去事件",
    choices: [
      ["present-perfect", "has checked"],
      ["past-simple", "checked"],
      ["present-perfect-continuous", "has been checking"],
      ["future-simple", "will check"],
    ],
  },
  {
    id: "present-perfect-continuous-01",
    lessonId: "present-perfect-continuous",
    context: "面包师从天亮起一直揉面，袖口和围裙上都沾满了面粉。",
    before: "The baker ",
    after: " dough since dawn.",
    whyCorrect: "动作从过去持续到现在，面粉痕迹也显示出持续过程。",
    contrast: "语境强调从天亮开始的揉面过程及其持续痕迹，而不是只报完成数量",
    choices: [
      ["present-perfect-continuous", "has been kneading"],
      ["present-perfect", "has kneaded"],
      ["past-simple", "kneaded"],
      ["present-continuous", "is kneading"],
    ],
  },
  {
    id: "present-perfect-continuous-02",
    lessonId: "present-perfect-continuous",
    context: "排练仍未结束，演奏者的手一直在发抖；接下来还要再排两小时。",
    before: "I ",
    after: " the cello for two hours without a break, and I still have another set to prepare.",
    whyCorrect: "排练仍在继续，持续时长和当前身体反应都让演奏过程成为重点。",
    contrast: "排练仍在继续，重点是到现在持续了多久，不是已经完成的演奏记录",
    choices: [
      ["present-perfect-continuous", "have been playing"],
      ["present-perfect", "have played"],
      ["past-perfect-continuous", "had been playing"],
      ["past-continuous", "was playing"],
    ],
  },
  {
    id: "present-perfect-continuous-03",
    lessonId: "present-perfect-continuous",
    context: "志愿者整个星期都在修人行桥，目前还剩最后一段没有完成。",
    before: "The volunteers ",
    after: " the footbridge all week.",
    whyCorrect: "维修从过去开始并延续到现在，且工程尚未完工。",
    contrast: "桥还没修完，句子突出一周以来持续进行的维修过程",
    choices: [
      ["present-perfect-continuous", "have been repairing"],
      ["present-perfect", "have repaired"],
      ["past-simple", "repaired"],
      ["future-continuous", "will be repairing"],
    ],
  },
  {
    id: "present-perfect-continuous-04",
    lessonId: "present-perfect-continuous",
    context: "雨整晚都敲打着屋顶，而且现在还没有停。",
    before: "It ",
    after: " nonstop since dark, and rain is still hitting the roof.",
    whyCorrect: "降雨从过去持续到现在且仍在继续，句子突出过程和时长。",
    contrast: "雨仍未停，表达的是持续中的降雨过程，而非已经结束的一场雨",
    choices: [
      ["present-perfect-continuous", "has been raining"],
      ["present-perfect", "has rained"],
      ["past-simple", "rained"],
      ["future-perfect-continuous", "will have been raining"],
    ],
  },
  {
    id: "present-perfect-continuous-05",
    lessonId: "present-perfect-continuous",
    context: "桥梁检查还在进行，工程师这两天一直在测量裂缝的变化。",
    before: "The engineers ",
    after: " the cracks since Monday.",
    whyCorrect: "测量从周一开始并延续至今，重点是连续进行的检查过程。",
    contrast: "检查仍在继续，语境关注持续活动，不是已经得到的测量结果",
    choices: [
      ["present-perfect-continuous", "have been measuring"],
      ["present-perfect", "have measured"],
      ["past-continuous", "were measuring"],
      ["present-simple", "measure"],
    ],
  },
  {
    id: "past-simple-01",
    lessonId: "past-simple",
    context: "上周二的签收记录确认了快递员取件的具体时间。",
    before: "At four last Tuesday, the courier ",
    after: " the signed package and left.",
    whyCorrect: "last Tuesday 是明确结束的过去时间，取件和离开也按顺序完成。",
    contrast: "这是有明确过去时间的已结束事件，不是连接现在的经历或更早的背景",
    choices: [
      ["past-simple", "collected"],
      ["past-continuous", "was collecting"],
      ["present-perfect", "has collected"],
      ["past-perfect", "had collected"],
    ],
  },
  {
    id: "past-simple-02",
    lessonId: "past-simple",
    context: "风暴后的检查发现，昨夜有人没有关好东侧大门。",
    before: "Who ",
    after: " the east gate open during the storm?",
    whyCorrect: "during the storm 指向一个已结束的过去事件，疑问句用 did 加动词原形。",
    contrast: "问题询问昨夜具体发生的事，不是在问现在的习惯或持续状态",
    choices: [
      ["past-simple", "left"],
      ["past-continuous", "was leaving"],
      ["present-perfect", "has left"],
      ["future-simple", "will leave"],
    ],
  },
  {
    id: "past-simple-03",
    lessonId: "past-simple",
    context: "终场哨响后，教练逐一走向球员。",
    before: "After the final whistle, the coach ",
    after: " each player by name.",
    whyCorrect: "哨声之后教练完成了一个有先后顺序的过去动作。",
    contrast: "场景讲述的是过去已经发生并完成的事件，不是当时正在进行的背景",
    choices: [
      ["past-simple", "congratulated"],
      ["past-continuous", "was congratulating"],
      ["past-perfect", "had congratulated"],
      ["present-simple", "congratulates"],
    ],
  },
  {
    id: "past-simple-04",
    lessonId: "past-simple",
    context: "旅行日记只记录了那趟京都之行中一次已经结束的参观。",
    before: "On her first trip to Kyoto, Lena ",
    after: " a small ceramics museum near the river.",
    whyCorrect: "日记叙述旅途中已经完成的一次参观。",
    contrast: "句子报告的是过去单次行程，不是现在的人生经历或过去某时的背景",
    choices: [
      ["past-simple", "visited"],
      ["present-perfect", "has visited"],
      ["past-continuous", "was visiting"],
      ["past-perfect", "had visited"],
    ],
  },
  {
    id: "past-simple-05",
    lessonId: "past-simple",
    context: "地方档案馆确认了老桥的坍塌年份。",
    before: "The old bridge ",
    after: " in 1987, and the town rebuilt it two years later.",
    whyCorrect: "1987 是明确结束的过去时间，坍塌和重建也构成过去事件顺序。",
    contrast: "事件有明确的过去年份，不应使用连接现在的完成时",
    choices: [
      ["past-simple", "collapsed"],
      ["present-perfect", "has collapsed"],
      ["past-perfect", "had collapsed"],
      ["future-simple", "will collapse"],
    ],
  },
  {
    id: "past-continuous-01",
    lessonId: "past-continuous",
    context: "主管昨晚九点走进实验室，看到两名技术员当时还没有停下校准。",
    before: "When the supervisor entered the lab at nine, two technicians ",
    after: " the machine.",
    whyCorrect: "主管走进实验室是过去参照点，校准当时仍在进行。",
    contrast: "校准是主管进入时正在展开的背景动作，不是已经完成的工作",
    choices: [
      ["past-continuous", "were calibrating"],
      ["past-simple", "calibrated"],
      ["past-perfect", "had calibrated"],
      ["present-continuous", "are calibrating"],
    ],
  },
  {
    id: "past-continuous-02",
    lessonId: "past-continuous",
    context: "搬动架子时玻璃突然裂开，碎片落在地板上。",
    before: "The glass broke while I ",
    after: " the shelf into place.",
    whyCorrect: "搬架子是玻璃破裂发生时仍在进行的背景动作。",
    contrast: "破裂打断了正在进行的搬动动作，背景要用过去进行时",
    choices: [
      ["past-continuous", "was lifting"],
      ["past-simple", "lifted"],
      ["past-perfect", "had lifted"],
      ["future-in-past-continuous", "would be lifting"],
    ],
  },
  {
    id: "past-continuous-03",
    lessonId: "past-continuous",
    context: "停电打断了游行，街上的乐队当时还在演奏。",
    before: "The street ",
    after: " with spectators when the power failed.",
    whyCorrect: "停电是过去的一个时间点，街道上聚满观众的过程当时仍在持续。",
    contrast: "停电发生时街道正在逐渐聚集人群，这是过去事件的背景过程",
    choices: [
      ["past-continuous", "was filling"],
      ["past-simple", "filled"],
      ["past-perfect", "had filled"],
      ["present-continuous", "is filling"],
    ],
  },
  {
    id: "past-continuous-04",
    lessonId: "past-continuous",
    context: "广播响起时，场馆里的人声盖过了播报内容。",
    before: "We couldn't hear the announcement because the crowd ",
    after: " so loudly.",
    whyCorrect: "听不清公告的原因，是当时人群正在持续欢呼。",
    contrast: "这里解释过去某一刻正在发生的背景声音，不是一次已结束的欢呼事件",
    choices: [
      ["past-continuous", "was cheering"],
      ["past-simple", "cheered"],
      ["past-perfect", "had cheered"],
      ["present-simple", "cheers"],
    ],
  },
  {
    id: "past-continuous-05",
    lessonId: "past-continuous",
    context: "最后一套戏服还在缝制，拉链突然松脱。",
    before: "Nora ",
    after: " the final costume when the zipper came loose.",
    whyCorrect: "拉链松脱发生时，Nora 正在缝制戏服。",
    contrast: "拉链问题打断了当时仍在进行的缝制过程",
    choices: [
      ["past-continuous", "was stitching"],
      ["past-simple", "stitched"],
      ["past-perfect", "had stitched"],
      ["present-perfect-continuous", "has been stitching"],
    ],
  },
  {
    id: "past-perfect-01",
    lessonId: "past-perfect",
    context: "学生到门口时发现进不去，只好等管理员回来。",
    before: "The class waited outside because the caretaker ",
    after: " the side door.",
    whyCorrect: "管理员锁门发生在学生开始等候之前，是两个过去事件中的较早一件。",
    contrast: "锁门先于过去的等候，句子需要标出更早的过去动作",
    choices: [
      ["past-perfect", "had locked"],
      ["past-simple", "locked"],
      ["past-continuous", "was locking"],
      ["present-perfect", "has locked"],
    ],
  },
  {
    id: "past-perfect-02",
    lessonId: "past-perfect",
    context: "编辑打开文件时，打印机已经连续吐出相同页面。",
    before: "When the editor opened the file, the printer ",
    after: " the same page thirty times.",
    whyCorrect: "重复打印在编辑打开文件之前已经发生，thirty times 强调已完成的次数。",
    contrast: "打印早于另一个明确的过去动作，而且强调先前累计完成的次数",
    choices: [
      ["past-perfect", "had printed"],
      ["past-simple", "printed"],
      ["past-continuous", "was printing"],
      ["present-perfect", "has printed"],
    ],
  },
  {
    id: "past-perfect-03",
    lessonId: "past-perfect",
    context: "徒步者抵达避难所时，暴风雨已经过去，天空开始放晴。",
    before: "By the time the hikers reached the shelter, the storm ",
    after: ".",
    whyCorrect: "暴风雨结束早于徒步者抵达这个过去参照点。",
    contrast: "暴风雨在他们抵达之前已经结束，两个过去事件需要明确先后",
    choices: [
      ["past-perfect", "had passed"],
      ["past-simple", "passed"],
      ["past-continuous", "was passing"],
      ["future-in-past-simple", "would pass"],
    ],
  },
  {
    id: "past-perfect-04",
    lessonId: "past-perfect",
    context: "我认出了那段旋律，随后才想起它曾出现在一部旧电影里。",
    before: "I recognised the melody because I ",
    after: " it in a film years earlier.",
    whyCorrect: "听到旋律的经历早于认出旋律这一过去时刻。",
    contrast: "电影里的听觉经历先于后来认出旋律的过去动作",
    choices: [
      ["past-perfect", "had heard"],
      ["past-simple", "heard"],
      ["present-perfect", "have heard"],
      ["past-continuous", "was hearing"],
    ],
  },
  {
    id: "past-perfect-05",
    lessonId: "past-perfect",
    context: "工程队先等许可文件，文件获批之后才开始施工。",
    before: "Before the permits arrived, the builder ",
    after: " any ground.",
    whyCorrect: "破土没有发生在许可到达之前，过去完成时否定结构标出这一先后关系。",
    contrast: "许可到达是过去参照点，参照点之前施工尚未开始",
    choices: [
      ["past-perfect", "hadn't broken"],
      ["past-simple", "didn't break"],
      ["past-continuous", "wasn't breaking"],
      ["future-in-past-simple", "wouldn't break"],
    ],
  },
  {
    id: "past-perfect-continuous-01",
    lessonId: "past-perfect-continuous",
    context: "救援船抵达时，划手们已经顶着逆流坚持了好几个小时。",
    before: "By the time the rescue boat reached them, the rowers ",
    after: " against the current for hours.",
    whyCorrect: "划船从过去较早时开始，一直持续到救援船抵达这一过去参照点。",
    contrast: "重点是到救援船抵达时已经持续了多久，而不是只报完成结果",
    choices: [
      ["past-perfect-continuous", "had been rowing"],
      ["past-perfect", "had rowed"],
      ["past-continuous", "were rowing"],
      ["present-perfect-continuous", "have been rowing"],
    ],
  },
  {
    id: "past-perfect-continuous-02",
    lessonId: "past-perfect-continuous",
    context: "客人到达前，工人整个上午都在粉刷大厅；房间里还留着明显的油漆气味。",
    before: "The hall smelled of paint because the crew ",
    after: " the walls all morning before the guests arrived.",
    whyCorrect: "粉刷持续了一段时间，并在客人到达前结束或暂停，留下现在的气味。",
    contrast: "语境强调到达前持续进行的粉刷过程及其留下的迹象",
    choices: [
      ["past-perfect-continuous", "had been painting"],
      ["past-perfect", "had painted"],
      ["past-continuous", "were painting"],
      ["present-perfect-continuous", "have been painting"],
    ],
  },
  {
    id: "past-perfect-continuous-03",
    lessonId: "past-perfect-continuous",
    context: "停电发生时，博物馆的电工眼睛已经很酸；标签从早餐后就一直在检查。",
    before: "When the power went out, the electrician ",
    after: " tiny labels since breakfast.",
    whyCorrect: "检查持续到停电这个过去时刻，since breakfast 突出持续时间。",
    contrast: "停电前的检查已经持续了一段时间，语境重在过程而非完成件数",
    choices: [
      ["past-perfect-continuous", "had been checking"],
      ["past-perfect", "had checked"],
      ["past-continuous", "was checking"],
      ["present-perfect-continuous", "has been checking"],
    ],
  },
  {
    id: "past-perfect-continuous-04",
    lessonId: "past-perfect-continuous",
    context: "引擎因为缺少润滑油而过热；检查记录显示问题已持续数日。",
    before: "The engine overheated after it ",
    after: " without enough oil for several days.",
    whyCorrect: "运转持续数日并导致后来过热，突出的是此前持续的原因过程。",
    contrast: "过热之前引擎已经持续运转数日，句子关注这一持续原因",
    choices: [
      ["past-perfect-continuous", "had been running"],
      ["past-perfect", "had run"],
      ["past-continuous", "was running"],
      ["present-perfect-continuous", "has been running"],
    ],
  },
  {
    id: "past-perfect-continuous-05",
    lessonId: "past-perfect-continuous",
    context: "Jules 中午终于打来电话，原来他从天亮起就一直在公交站等车。",
    before: "At noon, Jules finally called; he ",
    after: " at the bus depot since dawn.",
    whyCorrect: "等待从天亮开始并延续到中午这个过去参照点，since dawn 表示时长。",
    contrast: "电话打来时等待已持续数小时，重点是过去参照点前的持续过程",
    choices: [
      ["past-perfect-continuous", "had been waiting"],
      ["past-perfect", "had waited"],
      ["past-continuous", "was waiting"],
      ["present-perfect-continuous", "has been waiting"],
    ],
  },
  {
    id: "future-simple-01",
    lessonId: "future-simple",
    context: "会议室被重复预订，发言人当场决定把后半场改到阅览室连线。",
    before: "The meeting room is double-booked. I ",
    after: " the second half from the reading lounge.",
    whyCorrect: "说话人就在此刻作出决定，will 可表达即时决定。",
    contrast: "这是听到房间冲突之后才作出的临时决定，不是已经安排好的计划",
    choices: [
      ["future-simple", "will join"],
      ["present-continuous", "am joining"],
      ["present-simple", "join"],
      ["future-continuous", "will be joining"],
    ],
  },
  {
    id: "future-simple-02",
    lessonId: "future-simple",
    context: "同事正试图独自搬箱子，另一位同事马上主动帮忙。",
    before: "Don't carry those cartons alone; I ",
    after: " you with the last two.",
    whyCorrect: "I 后面是现场作出的主动承诺，will 表达即时提供帮助。",
    contrast: "说话人现在才提出帮忙，不是在描述未来某时正在进行的动作",
    choices: [
      ["future-simple", "will help"],
      ["present-continuous", "am helping"],
      ["future-continuous", "will be helping"],
      ["past-simple", "helped"],
    ],
  },
  {
    id: "future-simple-03",
    lessonId: "future-simple",
    context: "规划师根据河岸步道的设计图，谈谈它开放后可能带来的影响。",
    before: "I think the new footpath ",
    after: " more visitors to the wetland next spring.",
    whyCorrect: "说话人根据判断作出预测，will 常用于表达此类未来预测。",
    contrast: "这是对未来结果的看法，不是已有日历安排或某个时刻进行中的活动",
    choices: [
      ["future-simple", "will bring"],
      ["present-continuous", "is bringing"],
      ["future-continuous", "will be bringing"],
      ["past-simple", "brought"],
    ],
  },
  {
    id: "future-simple-04",
    lessonId: "future-simple",
    context: "项目负责人要让合作方放心，并作出明确承诺。",
    before: "I promise I ",
    after: " you the results before Friday.",
    whyCorrect: "promise 后的承诺用 will 表达说话人愿意完成的未来动作。",
    contrast: "句子是现在作出的承诺，不是从过去视角转述当时的预计",
    choices: [
      ["future-simple", "will email"],
      ["future-perfect", "will have emailed"],
      ["present-simple", "email"],
      ["future-in-past-simple", "would email"],
    ],
  },
  {
    id: "future-simple-05",
    lessonId: "future-simple",
    context: "天气预报员看着最新云图，判断傍晚海面上的风况。",
    before: "The forecaster expects the wind ",
    after: " before sunset.",
    whyCorrect: "expects 引出对未来天气的预测，will 表达预期结果。",
    contrast: "这里是对未来天气的预测，不是某个未来时刻正在发生的过程",
    choices: [
      ["future-simple", "will weaken"],
      ["future-continuous", "will be weakening"],
      ["present-simple", "weakens"],
      ["past-simple", "weakened"],
    ],
  },
  {
    id: "future-continuous-01",
    lessonId: "future-continuous",
    context: "路线安排显示，明天晚上八点车队会经过一段没有信号的山路。",
    before: "Please don't call at eight tomorrow; we ",
    after: " through the mountain tunnel then.",
    whyCorrect: "八点是明确的未来参照时刻，开车经过隧道届时正在进行。",
    contrast: "句子要表达八点那个未来时刻正在进行的活动，不只是预测是否会开车",
    choices: [
      ["future-continuous", "will be driving"],
      ["future-simple", "will drive"],
      ["future-perfect", "will have driven"],
      ["present-continuous", "are driving"],
    ],
  },
  {
    id: "future-continuous-02",
    lessonId: "future-continuous",
    context: "画廊下周开幕，工作人员想象展厅投入使用后的参观场景。",
    before: "At this time next week, visitors ",
    after: " through the new gallery.",
    whyCorrect: "at this time next week 指定未来某时，参观活动届时正在进行。",
    contrast: "重点是下周同一时刻正在发生的参观过程，而非届时已经完成的参观",
    choices: [
      ["future-continuous", "will be walking"],
      ["future-simple", "will walk"],
      ["future-perfect", "will have walked"],
      ["present-simple", "walk"],
    ],
  },
  {
    id: "future-continuous-03",
    lessonId: "future-continuous",
    context: "演出安排确定后，妹妹告知家人她傍晚六点的工作内容。",
    before: "At six this evening, my sister ",
    after: " her first radio broadcast.",
    whyCorrect: "句子关注傍晚六点这一未来时刻正在进行的播报。",
    contrast: "播报会在这个未来时点进行中，句子不是只说她会不会播报",
    choices: [
      ["future-continuous", "will be presenting"],
      ["future-simple", "will present"],
      ["future-perfect", "will have presented"],
      ["past-continuous", "was presenting"],
    ],
  },
  {
    id: "future-continuous-04",
    lessonId: "future-continuous",
    context: "你抵达港口时，我们会在灯塔附近等你的船。",
    before: "When you arrive at the harbor, we ",
    after: " for your boat near the lighthouse.",
    whyCorrect: "你到港口是未来参照点，等船的动作届时仍会持续。",
    contrast: "你抵达时等待正在进行，重点是未来时点中的活动状态",
    choices: [
      ["future-continuous", "will be waiting"],
      ["future-simple", "will wait"],
      ["future-perfect", "will have waited"],
      ["present-continuous", "are waiting"],
    ],
  },
  {
    id: "future-continuous-05",
    lessonId: "future-continuous",
    context: "下午三点要接来电的人正在交接工作，秘书说明届时会议室里的情况。",
    before: "At three tomorrow, the committee ",
    after: " the final draft in Room 4.",
    whyCorrect: "三点是未来时间点，委员会届时正在审阅草稿。",
    contrast: "句子描述未来某个具体时刻正在进行的审阅过程，不强调完成期限",
    choices: [
      ["future-continuous", "will be reviewing"],
      ["future-simple", "will review"],
      ["future-perfect", "will have reviewed"],
      ["past-continuous", "were reviewing"],
    ],
  },
  {
    id: "future-perfect-01",
    lessonId: "future-perfect",
    context: "餐饮团队正在安排宴会，所有桌面都必须在宾客到达前布置完毕。",
    before: "By the time the guests arrive, the caterer ",
    after: " every table.",
    whyCorrect: "宾客到达是未来截止点，布置桌子需要在那之前完成。",
    contrast: "关注截止时间前会完成的结果，而不是截止点上仍在布置",
    choices: [
      ["future-perfect", "will have set"],
      ["future-continuous", "will be setting"],
      ["future-simple", "will set"],
      ["present-perfect", "has set"],
    ],
  },
  {
    id: "future-perfect-02",
    lessonId: "future-perfect",
    context: "实习安排将在本月底轮换；导师盘点每位实习生届时完成的轮岗。",
    before: "At the end of this month, the interns ",
    after: " their pathology rotation.",
    whyCorrect: "月底是未来参照点，轮岗会在那时或之前完成。",
    contrast: "句子统计月底之前完成的轮岗成果，而不是月底仍在进行的工作",
    choices: [
      ["future-perfect", "will have completed"],
      ["future-continuous", "will be completing"],
      ["future-simple", "will complete"],
      ["past-perfect", "had completed"],
    ],
  },
  {
    id: "future-perfect-03",
    lessonId: "future-perfect",
    context: "维修队预计明天中午前修复主供水管，届时居民可重新用水。",
    before: "By noon tomorrow, the repair crew ",
    after: " the water line.",
    whyCorrect: "by noon tomorrow 给出未来完成期限，修复结果应在截止前出现。",
    contrast: "中午是未来截止点，强调到那时维修已经完成",
    choices: [
      ["future-perfect", "will have replaced"],
      ["future-continuous", "will be replacing"],
      ["future-simple", "will replace"],
      ["present-perfect", "has replaced"],
    ],
  },
  {
    id: "future-perfect-04",
    lessonId: "future-perfect",
    context: "起跑前，Amira 计划完成一圈热身，然后加入其他选手。",
    before: "By the time the race starts, Amira ",
    after: " her warm-up lap.",
    whyCorrect: "比赛开始是未来参照点，热身圈会在开始前完成。",
    contrast: "起跑时热身已经结束，重点是未来时点之前完成的动作",
    choices: [
      ["future-perfect", "will have finished"],
      ["future-continuous", "will be finishing"],
      ["future-simple", "will finish"],
      ["past-perfect", "had finished"],
    ],
  },
  {
    id: "future-perfect-05",
    lessonId: "future-perfect",
    context: "档案馆计划明年冬天搬迁，负责人列出搬迁前要完成的工作。",
    before: "By next winter, the staff ",
    after: " every document in the collection.",
    whyCorrect: "明年冬天是未来截止点，工作人员届时应已完成全部数字化。",
    contrast: "档案搬迁前要完成的是一项有明确未来期限的工作成果",
    choices: [
      ["future-perfect", "will have digitized"],
      ["future-continuous", "will be digitizing"],
      ["future-simple", "will digitize"],
      ["present-perfect", "have digitized"],
    ],
  },
  {
    id: "future-perfect-continuous-01",
    lessonId: "future-perfect-continuous",
    context: "诊所的移动医疗车服务即将满十年，主任介绍这项服务的持续历程。",
    before: "By December, the clinic ",
    after: " mobile units to rural towns for exactly ten years.",
    whyCorrect: "到十二月这一未来时点，派出医疗车的活动将持续满十年。",
    contrast: "表达截至未来时点已经持续的年数，重点是长期活动的过程",
    choices: [
      ["future-perfect-continuous", "will have been sending"],
      ["future-perfect", "will have sent"],
      ["future-continuous", "will be sending"],
      ["present-perfect-continuous", "has been sending"],
    ],
  },
  {
    id: "future-perfect-continuous-02",
    lessonId: "future-perfect-continuous",
    context: "夜班主管将在九点接手；白班团队从早上七点起一直在工作。",
    before: "At nine tonight, the crew ",
    after: " for fourteen hours, so the night supervisor will take over.",
    whyCorrect: "到九点这个未来参照点，工作将累计持续十四小时。",
    contrast: "强调到交班时为止已经持续了多久，而非到时完成多少工作",
    choices: [
      ["future-perfect-continuous", "will have been working"],
      ["future-perfect", "will have worked"],
      ["future-continuous", "will be working"],
      ["past-perfect-continuous", "had been working"],
    ],
  },
  {
    id: "future-perfect-continuous-03",
    lessonId: "future-perfect-continuous",
    context: "大学正在筹备校庆，校长介绍一位教授届时的任教年限。",
    before: "By the time the university celebrates its anniversary, Professor Lin ",
    after: " there for twenty-five years.",
    whyCorrect: "周年纪念是未来参照点，任教状态到那时将持续满二十五年。",
    contrast: "关注截至未来时点的任教时长，而不是仅仅说明已完成的任教次数",
    choices: [
      ["future-perfect-continuous", "will have been teaching"],
      ["future-perfect", "will have taught"],
      ["future-continuous", "will be teaching"],
      ["present-perfect-continuous", "has been teaching"],
    ],
  },
  {
    id: "future-perfect-continuous-04",
    lessonId: "future-perfect-continuous",
    context: "明年春天搬家时，我想算算自己在这套公寓住了多久。",
    before: "Next spring, I ",
    after: " in this apartment for three years.",
    whyCorrect: "明年春天是未来参照点，居住状态届时将持续满三年。",
    contrast: "句子计算持续到未来某时的居住时长，而非单次搬入事件",
    choices: [
      ["future-perfect-continuous", "will have been living"],
      ["future-perfect", "will have lived"],
      ["future-continuous", "will be living"],
      ["present-perfect-continuous", "have been living"],
    ],
  },
  {
    id: "future-perfect-continuous-05",
    lessonId: "future-perfect-continuous",
    context: "午夜关门时，志愿者将完成六小时的捐赠物资分类工作。",
    before: "When the gates close at midnight, the volunteers ",
    after: " donations for six hours.",
    whyCorrect: "午夜关门是未来参照点，分类活动届时将已持续六小时。",
    contrast: "需要表达截至午夜已经持续的时长，不只是当时正在分类",
    choices: [
      ["future-perfect-continuous", "will have been sorting"],
      ["future-perfect", "will have sorted"],
      ["future-continuous", "will be sorting"],
      ["past-perfect-continuous", "had been sorting"],
    ],
  },
  {
    id: "future-in-past-simple-01",
    lessonId: "future-in-past-simple",
    context: "早餐时父亲预报了当天稍晚的天气，结果积雪停在山谷上方。",
    before: "At breakfast, Dad said the snow ",
    after: " the valley before noon.",
    whyCorrect: "said 把视角放在过去，积雪抵达山谷则是从那时往后看的预期。",
    contrast: "句子转述过去作出的未来预测，不是现在的预测或过去已完成的事实",
    choices: [
      ["future-in-past-simple", "would reach"],
      ["future-simple", "will reach"],
      ["past-simple", "reached"],
      ["future-in-past-continuous", "would be reaching"],
    ],
  },
  {
    id: "future-in-past-simple-02",
    lessonId: "future-in-past-simple",
    context: "Mara 当时只知道最终公告还没发布，不清楚它后来带来的影响。",
    before: "Mara knew the final announcement ",
    after: " the crew.",
    whyCorrect: "从 knew 这个过去参照点看，announcement 带来的惊讶发生在之后。",
    contrast: "她在过去作出判断，惊讶的结果在那个判断时点之后才会出现",
    choices: [
      ["future-in-past-simple", "would surprise"],
      ["future-simple", "will surprise"],
      ["past-simple", "surprised"],
      ["future-in-past-perfect", "would have surprised"],
    ],
  },
  {
    id: "future-in-past-simple-03",
    lessonId: "future-in-past-simple",
    context: "多年后旧剧院改成了图书馆；叙述者回忆自己最初并不知道这件事。",
    before: "I didn't know the old theater ",
    after: " a library one day.",
    whyCorrect: "didn't know 是过去视角，改建是后来才发生的事。",
    contrast: "叙述者当时不知道之后会发生什么，不是在描述已经发生的改建",
    choices: [
      ["future-in-past-simple", "would become"],
      ["future-simple", "will become"],
      ["past-simple", "became"],
      ["past-perfect", "had become"],
    ],
  },
  {
    id: "future-in-past-simple-04",
    lessonId: "future-in-past-simple",
    context: "面试结束时，导演向每一位候选人作出回电承诺。",
    before: "During the interview, the director promised she ",
    after: " every candidate.",
    whyCorrect: "promised 提供过去参照点，回电动作安排在承诺之后。",
    contrast: "这是过去作出的承诺，不能把它写成现在的承诺或未来时点的进行动作",
    choices: [
      ["future-in-past-simple", "would call"],
      ["future-simple", "will call"],
      ["past-simple", "called"],
      ["future-in-past-continuous", "would be calling"],
    ],
  },
  {
    id: "future-in-past-simple-05",
    lessonId: "future-in-past-simple",
    context: "导航员在出发前预告雾会在第二天早晨散去。",
    before: "The navigator told us the fog ",
    after: " by morning.",
    whyCorrect: "told 把判断放在过去，雾散去是从那个时点往后看的预计。",
    contrast: "雾散是导航员当时预期的后续结果，而非现在的预测",
    choices: [
      ["future-in-past-simple", "would clear"],
      ["future-simple", "will clear"],
      ["past-simple", "cleared"],
      ["future-in-past-perfect", "would have cleared"],
    ],
  },
  {
    id: "future-in-past-continuous-01",
    lessonId: "future-in-past-continuous",
    context: "导游昨天说明，日落时队伍将走到一条宽阔的河边。",
    before: "The guide said that at sunset the hikers ",
    after: " a wide river.",
    whyCorrect: "said 是过去参照点，日落时的涉水过程从那个时点看将在之后进行。",
    contrast: "句子从过去的说明时点向前看，并突出日落时正在进行的涉水动作",
    choices: [
      ["future-in-past-continuous", "would be crossing"],
      ["future-in-past-simple", "would cross"],
      ["future-in-past-perfect", "would have crossed"],
      ["past-continuous", "were crossing"],
    ],
  },
  {
    id: "future-in-past-continuous-02",
    lessonId: "future-in-past-continuous",
    context: "出发前我以为孩子们会在我们到家时进入睡梦中。",
    before: "I thought the children ",
    after: " by the time we got home.",
    whyCorrect: "thought 是过去参照点，到家是其后的时间，入睡过程届时预计正在进行。",
    contrast: "这是从过去看向后来某一时刻的进行状态，不是单纯预测他们会睡着",
    choices: [
      ["future-in-past-continuous", "would be sleeping"],
      ["future-in-past-simple", "would sleep"],
      ["future-in-past-perfect", "would have slept"],
      ["past-continuous", "were sleeping"],
    ],
  },
  {
    id: "future-in-past-continuous-03",
    lessonId: "future-in-past-continuous",
    context: "他们在十点打来电话；我们知道乐团那时还在排练。",
    before: "When they called at ten, we knew the orchestra ",
    after: " then.",
    whyCorrect: "called 和 knew 都提供过去视角，排练是在那个过去时点之后的预期活动。",
    contrast: "排练被看作过去判断之后某个时段正在进行的活动",
    choices: [
      ["future-in-past-continuous", "would be rehearsing"],
      ["future-in-past-simple", "would rehearse"],
      ["past-continuous", "was rehearsing"],
      ["future-continuous", "will be rehearsing"],
    ],
  },
  {
    id: "future-in-past-continuous-04",
    lessonId: "future-in-past-continuous",
    context: "技术人员昨天安排了维护，预计服务器今晚会执行自动备份。",
    before: "Yesterday, the technician expected that tonight the server ",
    after: " a backup.",
    whyCorrect: "expected 是过去参照点，备份安排在之后的今晚并会持续一段时间。",
    contrast: "句子从昨天的预期出发，描述今晚届时正在进行的备份",
    choices: [
      ["future-in-past-continuous", "would be running"],
      ["future-in-past-simple", "would run"],
      ["future-in-past-perfect", "would have run"],
      ["future-continuous", "will be running"],
    ],
  },
  {
    id: "future-in-past-continuous-05",
    lessonId: "future-in-past-continuous",
    context: "昨天下午我预想自己去办公室时，建筑师会在工作室绘图。",
    before: "I imagined that when I reached the studio, the architect ",
    after: " the new entrance.",
    whyCorrect: "imagined 是过去参照点，到工作室是之后的时间，绘图预计届时仍在进行。",
    contrast: "重点是从过去视角想象将来某时正在进行的绘图过程",
    choices: [
      ["future-in-past-continuous", "would be sketching"],
      ["future-in-past-simple", "would sketch"],
      ["future-in-past-perfect", "would have sketched"],
      ["past-continuous", "was sketching"],
    ],
  },
  {
    id: "future-in-past-perfect-01",
    lessonId: "future-in-past-perfect",
    context: "制片人昨天承诺，在电影首映前她会把预告片剪辑完成。",
    before: "The producer promised that she ",
    after: " the trailer by opening night.",
    whyCorrect: "promised 是过去参照点，剪辑完成要早于之后的首映之夜。",
    contrast: "需要表达从过去视角看，首映这个未来期限之前会完成的结果",
    choices: [
      ["future-in-past-perfect", "would have edited"],
      ["future-in-past-simple", "would edit"],
      ["future-in-past-continuous", "would be editing"],
      ["past-perfect", "had edited"],
    ],
  },
  {
    id: "future-in-past-perfect-02",
    lessonId: "future-in-past-perfect",
    context: "冬季来临前，大家预计西翼屋顶的维修会结束。",
    before: "We expected the roofers ",
    after: " the west wing before winter arrived.",
    whyCorrect: "expected 是过去参照点，完工要发生在随后到来的冬季之前。",
    contrast: "过去的预期指向一个更晚的截止时间，并要求那之前已经完成维修",
    choices: [
      ["future-in-past-perfect", "would have finished"],
      ["future-in-past-simple", "would finish"],
      ["future-in-past-continuous", "would be finishing"],
      ["past-perfect", "had finished"],
    ],
  },
  {
    id: "future-in-past-perfect-03",
    lessonId: "future-in-past-perfect",
    context: "出发前他告诉我们，等我们回来时他会把设备全部放好。",
    before: "He said that by the time we returned, he ",
    after: " all the equipment in place.",
    whyCorrect: "said 提供过去视角，returned 是其后的参照点，放置工作要在那之前完成。",
    contrast: "设备放置被看作在后来返回这一时点之前就会完成的结果",
    choices: [
      ["future-in-past-perfect", "would have put"],
      ["future-in-past-simple", "would put"],
      ["future-in-past-continuous", "would be putting"],
      ["past-perfect", "had put"],
    ],
  },
  {
    id: "future-in-past-perfect-04",
    lessonId: "future-in-past-perfect",
    context: "首班飞机起飞前，天气预报预计工作人员会清理完跑道。",
    before: "The forecast predicted they ",
    after: " the runway before the first flight.",
    whyCorrect: "predicted 是过去参照点，清理完成要早于之后的首班飞机。",
    contrast: "这是过去作出的预测，关注未来截止点之前完成的清理成果",
    choices: [
      ["future-in-past-perfect", "would have cleared"],
      ["future-in-past-simple", "would clear"],
      ["future-in-past-continuous", "would be clearing"],
      ["future-perfect", "will have cleared"],
    ],
  },
  {
    id: "future-in-past-perfect-05",
    lessonId: "future-in-past-perfect",
    context: "六月到来前，Anna 相信自己能攒够租用工作室的费用。",
    before: "Anna believed she ",
    after: " enough by June to rent a studio.",
    whyCorrect: "believed 是过去参照点，存够钱的结果预计会在之后的六月前实现。",
    contrast: "她在过去判断某个更晚期限前会完成储蓄目标",
    choices: [
      ["future-in-past-perfect", "would have saved"],
      ["future-in-past-simple", "would save"],
      ["future-in-past-continuous", "would be saving"],
      ["future-perfect", "will have saved"],
    ],
  },
  {
    id: "future-in-past-perfect-continuous-01",
    lessonId: "future-in-past-perfect-continuous",
    context: "五月初，植物学家预计到仲夏时，团队追踪这群鸟就满一年了。",
    before: "In early May, the botanist expected that by midsummer the team ",
    after: " the flock for a year.",
    whyCorrect: "expected 是过去视角，追踪活动会持续到更晚的仲夏参照点并满一年。",
    contrast: "关注从过去判断点看，持续到未来参照点时将累计多久",
    choices: [
      ["future-in-past-perfect-continuous", "would have been tracking"],
      ["future-in-past-perfect", "would have tracked"],
      ["future-in-past-continuous", "would be tracking"],
      ["past-perfect-continuous", "had been tracking"],
    ],
  },
  {
    id: "future-in-past-perfect-continuous-02",
    lessonId: "future-in-past-perfect-continuous",
    context: "船到港口之前，船员估计引擎已经连续运转六个小时。",
    before: "They assumed the engine ",
    after: " for six hours by the time the ship reached port.",
    whyCorrect: "assumed 是过去参照点，引擎运行时长会累计到之后的抵港时刻。",
    contrast: "句子计算到未来抵港时为止的持续时间，而不是只说明届时引擎在运行",
    choices: [
      ["future-in-past-perfect-continuous", "would have been running"],
      ["future-in-past-perfect", "would have run"],
      ["future-in-past-continuous", "would be running"],
      ["past-perfect-continuous", "had been running"],
    ],
  },
  {
    id: "future-in-past-perfect-continuous-03",
    lessonId: "future-in-past-perfect-continuous",
    context: "电影节开幕前，导演估计摄制组的拍摄期将满三个月。",
    before: "The director thought that by the festival the crew ",
    after: " for three months.",
    whyCorrect: "thought 是过去视角，拍摄会持续到之后的电影节，并在那时满三个月。",
    contrast: "重点是从过去参照点往后计算持续到电影节的拍摄时长",
    choices: [
      ["future-in-past-perfect-continuous", "would have been filming"],
      ["future-in-past-perfect", "would have filmed"],
      ["future-in-past-continuous", "would be filming"],
      ["past-perfect-continuous", "had been filming"],
    ],
  },
  {
    id: "future-in-past-perfect-continuous-04",
    lessonId: "future-in-past-perfect-continuous",
    context: "上周五评审时，工程师预计到发射日，新传感器测试就满四周。",
    before: "At last Friday's review, engineers expected that by launch the rover ",
    after: " the new sensor for four weeks.",
    whyCorrect: "expected 是过去参照点，测试持续到更晚的发射日时会满四周。",
    contrast: "语境关注截至未来发射时点已经持续的测试时长",
    choices: [
      ["future-in-past-perfect-continuous", "would have been testing"],
      ["future-in-past-perfect", "would have tested"],
      ["future-in-past-continuous", "would be testing"],
      ["future-perfect-continuous", "will have been testing"],
    ],
  },
  {
    id: "future-in-past-perfect-continuous-05",
    lessonId: "future-in-past-perfect-continuous",
    context: "九月结束时，他预计自己执教这支队伍将满十年。",
    before: "He knew that by the end of September, he ",
    after: " the team for a decade.",
    whyCorrect: "knew 是过去参照点，执教会延续到之后的九月底并满十年。",
    contrast: "句子强调持续到未来期限的执教时长，而非只表达届时的身份",
    choices: [
      ["future-in-past-perfect-continuous", "would have been coaching"],
      ["future-in-past-perfect", "would have coached"],
      ["future-in-past-continuous", "would be coaching"],
      ["past-perfect-continuous", "had been coaching"],
    ],
  },
]

export const mixedPracticeQuestions: LessonQuestion[] = mixedQuestionSeeds.map(
  (seed) => {
    const targetLesson = getTenseLessonById(seed.lessonId)
    if (!targetLesson) throw new Error(`Unknown mixed-practice lesson: ${seed.lessonId}`)

    const feedbackByOption = Object.fromEntries(
      seed.choices.map(([choiceLessonId]) => {
        const choiceLesson = getTenseLessonById(choiceLessonId)
        if (!choiceLesson) {
          throw new Error(`Unknown mixed-practice choice: ${choiceLessonId}`)
        }

        const feedback =
          choiceLessonId === seed.lessonId
            ? `正确。${seed.whyCorrect}`
            : `${choiceLesson.title}通常用于${choiceLesson.summary}；但${seed.contrast}，所以这里更适合${targetLesson.title}。`

        return [choiceLessonId, feedback]
      }),
    )

    return {
      id: `mixed-${seed.id}`,
      lessonId: seed.lessonId,
      context: seed.context,
      before: seed.before,
      after: seed.after,
      options: seed.choices.map(([lessonId, label]) => ({ id: lessonId, label })),
      correctOptionId: seed.lessonId,
      feedbackByOption,
      practiceStage: "16 时态混合练习",
    }
  },
)

export const mixedPracticeQuestionIds = mixedPracticeQuestions.map(
  (question) => question.id,
)

export const allProgressQuestionIds = [...
  new Set([
    ...tenseLessons.flatMap((lesson) => [
      lesson.guidedQuestion.id,
      ...lesson.practiceQuestions.map((question) => question.id),
      lesson.transferQuestion.id,
    ]),
    ...mixedPracticeQuestionIds,
  ]),
]

function shuffled<T>(items: T[], random: () => number): T[] {
  const result = [...items]
  for (let index = result.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(random() * (index + 1))
    ;[result[index], result[swapIndex]] = [result[swapIndex], result[index]]
  }
  return result
}

export function createMixedPracticeRound(random: () => number = Math.random) {
  const selectedByLesson = tenseLessons.map((lesson) => {
    const questions = mixedPracticeQuestions.filter(
      (question) => question.lessonId === lesson.id,
    )
    const question = questions[Math.floor(random() * questions.length)]
    if (!question) throw new Error(`No mixed-practice questions for ${lesson.id}`)
    return { ...question, options: shuffled(question.options, random) }
  })

  return shuffled(selectedByLesson, random)
}
