import type { LessonQuestion } from "@/features/tenses/lesson-data"

type AnswerSeed = readonly [id: string, label: string, feedback: string]

function makeLessonQuestion(
  id: string,
  lessonId: string,
  practiceStage: string,
  context: string,
  before: string,
  after: string,
  correctOptionId: string,
  answers: readonly AnswerSeed[],
): LessonQuestion {
  return {
    id,
    lessonId,
    practiceStage,
    context,
    before,
    after,
    options: answers.map(([optionId, label]) => ({ id: optionId, label })),
    correctOptionId,
    feedbackByOption: Object.fromEntries(
      answers.map(([optionId, , feedback]) => [optionId, feedback]),
    ),
  }
}

function practiceQuestion(
  lessonId: string,
  number: 1 | 2 | 3,
  practiceStage: string,
  context: string,
  before: string,
  after: string,
  correctOptionId: string,
  answers: readonly AnswerSeed[],
): LessonQuestion {
  return makeLessonQuestion(
    `practice-${lessonId}-${number}`,
    lessonId,
    practiceStage,
    context,
    before,
    after,
    correctOptionId,
    answers,
  )
}

export const guidedQuestionsByLesson: Record<string, LessonQuestion> = {
  "present-simple": makeLessonQuestion(
    "guided-present-simple-independent",
    "present-simple",
    "导学题",
    "这是对极地熊觅食习惯的一般说明，不是在讲某一次捕猎。",
    "A polar bear ",
    " on sea ice to hunt.",
    "simple",
    [
      ["simple", "hunts", "正确。句子说明这种动物通常怎样觅食，是一般事实；单数主语搭配 hunts。"],
      ["continuous", "is hunting", "is hunting 描述某只熊眼下正在捕猎；此处说的是普遍习性。"],
      ["perfect", "has hunted", "has hunted 需要一个与现在相关的经历或时段；题目没有说一次捕猎已经完成。"],
      ["past", "hunted", "hunted 把捕猎放在过去某次；句子概括的是一般行为。"],
    ],
  ),
  "present-continuous": makeLessonQuestion(
    "guided-present-continuous-studio",
    "present-continuous",
    "导学题",
    "透过摄影棚玻璃看进去，摄影师此刻正在调整灯光。",
    "Look through the studio window: the photographer ",
    " the lights right now.",
    "continuous",
    [
      ["continuous", "is adjusting", "正确。right now 和眼前观察到的动作都表明灯光调整正在进行。"],
      ["simple", "adjusts", "adjusts 更像固定工作习惯；这里描述摄影师此刻正在做什么。"],
      ["perfect", "has adjusted", "has adjusted 表示灯光已经调好；语境显示调整过程仍在继续。"],
      ["past", "was adjusting", "was adjusting 把动作放在过去某时；right now 将观察点放在现在。"],
    ],
  ),
  "present-perfect": makeLessonQuestion(
    "guided-present-perfect-experience",
    "present-perfect",
    "导学题",
    "这是 Mina 到现在都没有过的一次经历；她正听向导介绍如何上马。",
    "Mina ",
    " a horse before, so the guide is showing her how to mount.",
    "perfect",
    [
      ["perfect", "has never ridden", "正确。before 和向导正在帮助她的当前情境，把此前的人生经历连到现在。"],
      ["past", "never rode", "never rode 通常需要已结束的过去时段；这里总结截至现在的经历。"],
      ["past-perfect", "had never ridden", "had never ridden 需要另一个过去参照点；题目谈的是 Mina 到现在的经历。"],
      ["continuous", "is never riding", "is never riding 不自然地描述此刻动作；句子表达的是从未有过的经历。"],
    ],
  ),
  "present-perfect-continuous": makeLessonQuestion(
    "guided-present-perfect-continuous-renovation",
    "present-perfect-continuous",
    "导学题",
    "邻居家的厨房翻修还在进行；从开工到现在已经六周。",
    "The neighbors ",
    " their kitchen for six weeks, and the renovation is still underway.",
    "perfect-continuous",
    [
      ["perfect-continuous", "have been renovating", "正确。翻修从过去持续到现在且尚未结束；for six weeks 突出持续过程。"],
      ["perfect", "have renovated", "have renovated 更突出完成的翻修成果；句子明确说工程仍在进行。"],
      ["continuous", "are renovating", "are renovating 说明现在正在翻修，但没有表达已经持续六周。"],
      ["past", "renovated", "renovated 把翻修放在已结束的过去；这里工程还没有结束。"],
    ],
  ),
  "past-simple": makeLessonQuestion(
    "guided-past-simple-fair",
    "past-simple",
    "导学题",
    "科学展昨天已经结束；Jo 当天向评委展示了一辆太阳能小车。",
    "At yesterday's science fair, Jo ",
    " her solar-powered car to the judges.",
    "past",
    [
      ["past", "presented", "正确。yesterday 给出已结束的过去时间；present 的过去式是 presented。"],
      ["continuous", "was presenting", "was presenting 把展示呈现为过去某时的进行过程；这里回顾完整的一次展示。"],
      ["perfect", "has presented", "现在完成时通常不与 yesterday 这样的结束时间直接搭配。"],
      ["past-perfect", "had presented", "had presented 需要另一个过去参照点来说明更早的展示；句中只有一次已结束的事件。"],
    ],
  ),
  "past-continuous": makeLessonQuestion(
    "guided-past-continuous-bakery",
    "past-continuous",
    "导学题",
    "送货卡车到达时，烘焙师仍在烤当天的面包。",
    "At 8:15, the baker ",
    " fresh rolls when the delivery truck arrived.",
    "continuous",
    [
      ["continuous", "was baking", "正确。卡车到达是过去的短事件；烘焙当时正在进行，构成背景。"],
      ["simple", "baked", "baked 会把烘焙说成完整事件；语境强调卡车到达时动作仍在继续。"],
      ["past-perfect", "had baked", "had baked 表示面包在卡车到达前已经烤好；语境说烘焙师当时仍在烤。"],
      ["future", "will be baking", "will be baking 指向未来；8:15 和卡车到达都属于过去场景。"],
    ],
  ),
  "past-perfect": makeLessonQuestion(
    "guided-past-perfect-address",
    "past-perfect",
    "导学题",
    "先找到正确地址，后来才能把表格寄出；句子要明确标出这个先后关系。",
    "I could send the form because I ",
    " the correct address earlier.",
    "past-perfect",
    [
      ["past-perfect", "had found", "正确。寄出表格是过去参照点；找到地址发生在之前，用 had found 标出较早动作。"],
      ["past", "found", "found 也能叙述过去事件；题目特别强调它先于寄出表格发生。"],
      ["continuous", "was finding", "was finding 表示寻找过程当时正在发生；这里需要表达地址已先找到。"],
      ["present-perfect", "have found", "have found 把找到的结果连到现在；句子的两个事件都在过去。"],
    ],
  ),
  "past-perfect-continuous": makeLessonQuestion(
    "guided-past-perfect-continuous-mural",
    "past-perfect-continuous",
    "导学题",
    "休息开始时，Jo 的手上沾满蓝色颜料；粉刷此前已持续近三小时。",
    "Her hands were blue by the time break started; she ",
    " the stage props for almost three hours.",
    "past-perfect-continuous",
    [
      ["past-perfect-continuous", "had been painting", "正确。休息开始是过去参照点；此前持续近三小时的粉刷过程解释了颜料。"],
      ["past-perfect", "had painted", "had painted 更突出已经完成的粉刷结果；这里强调的是此前持续的过程和时长。"],
      ["past-continuous", "was painting", "was painting 表示休息开始时正在粉刷，但没有突出此前已持续近三小时。"],
      ["present-perfect-continuous", "has been painting", "has been painting 将过程连到现在；句子的参照点是已经过去的休息开始时。"],
    ],
  ),
  "future-simple": makeLessonQuestion(
    "guided-future-will-paper",
    "future-simple",
    "导学题",
    "刚发现打印机没有纸，说话人现在才决定去办公室储物柜找。",
    "We're out of printer paper. I ",
    " the office cupboard.",
    "will",
    [
      ["will", "will check", "正确。缺纸的情况刚被发现，说话人当场决定去检查储物柜。"],
      ["continuous", "am checking", "am checking 更像已经安排或正在执行的检查；这里的决定刚刚作出。"],
      ["past", "checked", "checked 表示已经检查过；说话人现在才提出去找纸。"],
      ["perfect", "have checked", "have checked 表示到现在已经检查；题目说的是当前作出的下一步决定。"],
    ],
  ),
  "future-continuous": makeLessonQuestion(
    "guided-future-continuous-valley",
    "future-continuous",
    "导学题",
    "路线安排显示，上午十一点是穿越河谷的中途时刻，队伍届时仍在行进。",
    "At eleven, the hikers ",
    " the river valley, according to the route plan.",
    "future-continuous",
    [
      ["future-continuous", "will be crossing", "正确。上午十一点是未来观察点；届时穿越河谷的活动仍在进行。"],
      ["future-simple", "will cross", "will cross 说明将来会穿越，但没有呈现十一点时正在进行的画面。"],
      ["future-perfect", "will have crossed", "will have crossed 表示到十一点前已穿过河谷；路线说那时还在途中。"],
      ["past", "crossed", "crossed 把穿越放在过去；这里描述未来路线安排。"],
    ],
  ),
  "future-perfect": makeLessonQuestion(
    "guided-future-perfect-sorter",
    "future-perfect",
    "导学题",
    "分拣机计数器显示已处理十九件；按当前速度，到五点会处理完第二十件。",
    "By five, the sorter ",
    " its twentieth parcel.",
    "future-perfect",
    [
      ["future-perfect", "will have processed", "正确。五点是未来参照点；到那时第二十件预计已经处理完成。"],
      ["future-simple", "will process", "will process 表示将来会处理；will have processed 更明确地突出五点前完成。"],
      ["future-continuous", "will be processing", "will be processing 表示五点时仍在处理；语境说第二十件届时会完成。"],
      ["present-perfect", "has processed", "has processed 从现在总结已有结果；句中的完成时点在未来五点。"],
    ],
  ),
  "future-perfect-continuous": makeLessonQuestion(
    "guided-future-perfect-continuous-clock",
    "future-perfect-continuous",
    "导学题",
    "修复工作仍在继续；时钟重新挂回墙上时，Mei 的修复时长预计正好两个月。",
    "By the time the clock is rehung, Mei ",
    " it for two months.",
    "future-perfect-continuous",
    [
      ["future-perfect-continuous", "will have been restoring", "正确。重新挂回是未来参照点；for two months 强调到那时已持续的修复过程。"],
      ["future-perfect", "will have restored", "will have restored 更强调届时完成的结果；题目关注此前持续两个月的过程。"],
      ["future-continuous", "will be restoring", "will be restoring 描述某个未来时刻正在修复，但没有表达届时已持续多久。"],
      ["past-perfect-continuous", "had been restoring", "had been restoring 以过去时点为参照；时钟重新挂回还在未来。"],
    ],
  ),
  "future-in-past-simple": makeLessonQuestion(
    "guided-future-in-past-launch",
    "future-in-past-simple",
    "导学题",
    "四月的计划会上，团队认为新应用会在六月发布；这里从当时的视角转述。",
    "At the April planning meeting, the team thought the new app ",
    " in June.",
    "would",
    [
      ["would", "would launch", "正确。thought 是过去参照点；六月发布在之后，用 would 表示过去视角的未来。"],
      ["will", "will launch", "will 从现在视角指向未来；句子转述的是团队当时的预期。"],
      ["past-perfect", "had launched", "had launched 表示应用在计划会之前已经发布；六月还在当时的未来。"],
      ["would-perfect", "would have launched", "would have launched 会从过去看向更晚时点并强调届时已完成；此处只说预期的发布。"],
    ],
  ),
  "future-in-past-continuous": makeLessonQuestion(
    "guided-future-in-past-continuous-sailing",
    "future-in-past-continuous",
    "导学题",
    "船长昨天介绍次日航线时说，日出时船员仍会驶在灯塔以外的海面上。",
    "Yesterday, the captain said that at sunrise the crew ",
    " beyond the lighthouse.",
    "would-continuous",
    [
      ["would-continuous", "would be sailing", "正确。said 是过去参照点；日出在之后，be sailing 描述届时正在进行的航行。"],
      ["would", "would sail", "would sail 说明之后会航行，但没有表达日出时正在进行的状态。"],
      ["past-perfect", "had sailed", "had sailed 把航行放在船长说话之前；日出时刻在之后。"],
      ["will-continuous", "will be sailing", "will be sailing 从现在角度谈未来；这里转述船长昨天的说法。"],
    ],
  ),
  "future-in-past-perfect": makeLessonQuestion(
    "guided-future-in-past-perfect-receipts",
    "future-in-past-perfect",
    "导学题",
    "周一经理预计，会计在周二审计前就能整理好所有收据。",
    "On Monday, the manager expected the accountant ",
    " all the receipts before Tuesday's audit.",
    "would-perfect",
    [
      ["would-perfect", "would have filed", "正确。周一是过去的预期点，周二审计在后；收据预计此前已整理完成。"],
      ["past-perfect", "had filed", "had filed 表示收据在周一预期之前就已整理好；题目说的是之后的预计结果。"],
      ["would", "would file", "would file 只说之后会整理；完成时更明确表达审计前已经完成。"],
      ["future-perfect", "will have filed", "will have filed 从现在角度看向未来；这里报告的是经理周一作出的预期。"],
    ],
  ),
  "future-in-past-perfect-continuous": makeLessonQuestion(
    "guided-future-in-past-perfect-continuous-soundtrack",
    "future-in-past-perfect-continuous",
    "导学题",
    "二月时作曲家预计到十月，配乐创作将持续八个月，而且当时仍有曲目未完成。",
    "In February, the composer expected that by October she ",
    " on the soundtrack for eight months.",
    "would-perfect-continuous",
    [
      ["would-perfect-continuous", "would have been working", "正确。二月是过去预期点，十月在后；持续八个月且仍未完成，强调届时的创作过程。"],
      ["would-perfect", "would have worked", "would have worked 更像概括届时完成的工作；这里明确说创作仍未完成。"],
      ["past-perfect-continuous", "had been working", "had been working 把创作时长放在二月之前；句子计算的是到十月的时长。"],
      ["future-perfect-continuous", "will have been working", "will have been working 从现在看向未来；句子转述的是作曲家二月的预期。"],
    ],
  ),
}

export const closeDistractorsByQuestion: Record<string, AnswerSeed> = {
  "transfer-routine": ["nearby", "had played", "had played places the basketball routine before another past point; this sentence describes Leo's current weekday habit."],
  "transfer-action-now": ["nearby", "had been taking", "had been taking needs a later past reference point; the friends can see Leo's shot happening now."],
  "transfer-present-perfect-so-far": ["nearby", "had read", "had read places the reading before another past point; so far today measures Nina's total up to now."],
  "transfer-present-perfect-continuous-rain": ["nearby", "had been raining", "had been raining looks back from a past reference point; the rain explains the wet ground now."],
  "transfer-past-simple-concert": ["nearby", "will have started", "will have started looks ahead to a future point; the concert started at a specific time yesterday."],
  "transfer-past-continuous-setting-table": ["nearby", "will have been setting", "will have been setting looks forward from now to a future duration; Hana was setting the table during a past event."],
  "transfer-past-perfect-report": ["nearby", "will have sent", "will have sent describes completion before a future point; the manager's call is a past reference point."],
  "transfer-past-perfect-continuous-garden": ["nearby", "will have been working", "will have been working measures duration up to a future point; noon is the past reference point in this sentence."],
  "transfer-future-will-window": ["nearby", "had closed", "had closed places the action before another past point; the speaker is deciding what to do now."],
  "transfer-future-continuous-study": ["nearby", "had been studying", "had been studying looks back from a past reference point; tonight is still in the future."],
  "transfer-future-perfect-dinner": ["nearby", "had prepared", "had prepared places dinner before another past point; the guests' arrival has not happened yet."],
  "transfer-future-perfect-continuous-driving": ["nearby", "had been driving", "had been driving measures duration up to a past point; six p.m. is the future reference time."],
  "transfer-future-in-past-simple-call": ["nearby", "will have called", "will have called looks forward from now; Nina's promise was made yesterday and concerns a later call."],
  "transfer-future-in-past-continuous-drive": ["nearby", "had still been driving", "had still been driving describes driving before a past point; seven o'clock comes after Nina spoke at six."],
  "transfer-future-in-past-perfect-edit": ["nearby", "will have edited", "will have edited looks ahead from the present; the sentence reports Thursday's expectation about Monday."],
  "transfer-future-in-past-perfect-continuous-bridge": ["nearby", "will have been working", "will have been working measures duration from the present viewpoint; the crew's expectation was made in March."],
}

export const practiceQuestionsByLesson: Record<string, LessonQuestion[]> = {
  "present-simple": [
    practiceQuestion(
      "present-simple",
      1,
      "线索辨析",
      "Nina 的固定习惯；她每节课都这样做。",
      "Nina usually ",
      " her phone on silent during lessons.",
      "simple",
      [
        ["simple", "puts", "正确。usually 和每节课都做的安排共同表达稳定习惯；Nina 是第三人称单数，所以用 puts。"],
        ["continuous", "is putting", "is putting 描述此刻正在操作手机；句意强调她反复保持的课堂习惯。"],
        ["perfect", "has put", "has put 强调已完成动作与现在的联系；这里没有某次已完成的动作或结果。"],
        ["past", "put", "put 可描述过去的一次动作；这里说的是 Nina 现在通常会做什么。"],
      ],
    ),
    practiceQuestion(
      "present-simple",
      2,
      "相近形式",
      "这是博物馆官网公布的常规开放时间，不是一次临时安排。",
      "According to the timetable, the museum ",
      " at 10 every Sunday.",
      "simple",
      [
        ["continuous", "is opening", "is opening 更常描述某次正在发生或已安排的活动；这里列出每周重复的开放时间。"],
        ["simple", "opens", "正确。固定时间表可用一般现在时；every Sunday 明确表示常规安排。"],
        ["future", "will open", "will open 可以谈将来，但这里不是一次未来决定，而是官网公布的重复时间表。"],
        ["perfect", "has opened", "has opened 表示开门动作已经发生并与现在相关；句子说的是常规开放时间。"],
      ],
    ),
    practiceQuestion(
      "present-simple",
      3,
      "综合语境",
      "Sam 不是在看地图；他已经熟悉这条路，正在解释自己平时怎么走。",
      "I ",
      " this route well, so I can guide you without a map.",
      "simple",
      [
        ["continuous", "am knowing", "know 表示掌握某项知识或熟悉某事时通常用状态动词形式，不用 am knowing。"],
        ["past", "knew", "knew 把熟悉这条路放在过去；but 后面的现在能力说明这种熟悉仍然成立。"],
        ["simple", "know", "正确。know 在这里表示稳定的认知状态，与现在仍能带路的事实相连。"],
        ["perfect", "have known", "have known 常要说明从何时开始熟悉；这里自然表达的是当前状态，后面没有持续起点。"],
      ],
    ),
  ],
  "present-continuous": [
    practiceQuestion(
      "present-continuous",
      1,
      "线索辨析",
      "Mia 正在进行线上考试；现在不要打电话打断她。",
      "Please don't call Mia now; she ",
      " an online exam.",
      "continuous",
      [
        ["simple", "takes", "takes 更像日常习惯；now 和不要打断她表明考试正在进行。"],
        ["continuous", "is taking", "正确。此刻正在进行的活动用 is + -ing；Mia 对应 is taking。"],
        ["perfect", "has taken", "has taken 表示考试已经参加过或已完成；这里 Mia 现在仍在考试。"],
        ["past-continuous", "was taking", "was taking 描述过去某时正在考试；句子中的 now 把观察点放在现在。"],
      ],
    ),
    practiceQuestion(
      "present-continuous",
      2,
      "相近形式",
      "厨房正在维修，这一家人只在姨妈家暂住这个月。",
      "This month, we ",
      " with my aunt while our kitchen is repaired.",
      "continuous",
      [
        ["simple", "stay", "stay 可描述固定住处或习惯；this month 表示当前阶段的临时安排。"],
        ["perfect", "have stayed", "have stayed 会把已经发生的住宿经历连到现在；这里强调暂时状态仍在持续。"],
        ["continuous", "are staying", "正确。现在进行时也能描述当前一段时间的临时情况；we 用 are。"],
        ["past", "stayed", "stayed 表示已结束的过去住宿；厨房维修期间的暂住还没有结束。"],
      ],
    ),
    practiceQuestion(
      "present-continuous",
      3,
      "综合语境",
      "说话人看见对方正拿着自己的笔记，而且自己正在使用它们。",
      "Why ",
      " my notes while I'm using them?",
      "continuous",
      [
        ["simple", "do you read", "do you read 会问阅读习惯；这里质问的是正在发生的动作。"],
        ["perfect", "have you read", "have you read 会问已经读过的经历或结果；对方此刻正在看笔记。"],
        ["past", "were you reading", "were you reading 把动作放在过去某时；说话人现在就在看见这个动作。"],
        ["continuous", "are you reading", "正确。对当前正在进行的行为提问，用 are + 主语 + -ing。"],
      ],
    ),
  ],
  "present-perfect": [
    practiceQuestion(
      "present-perfect",
      1,
      "线索辨析",
      "我检查过大厅了，现在仍找不到眼镜，所以看不清告示。",
      "I ",
      " my glasses anywhere, so I can't read the sign.",
      "perfect",
      [
        ["past", "didn't find", "didn't find 通常把搜索放在一个已结束的过去时段；这里结果直接影响现在。"],
        ["perfect", "haven't found", "正确。到现在仍没找到，否定的经历与眼下看不清告示相连。"],
        ["past-perfect", "hadn't found", "hadn't found 需要另一个过去参照点；这句话的结果落在现在。"],
        ["continuous", "haven't been finding", "find 在这里表示找到这个结果，通常不用于强调持续进行的动作过程。"],
      ],
    ),
    practiceQuestion(
      "present-perfect",
      2,
      "相近形式",
      "本年度还没有结束；到目前为止我们已去过三次。",
      "We ",
      " that museum three times so far this year.",
      "perfect",
      [
        ["past", "visited", "visited 常用于已结束的过去时间段；so far this year 表示今年目前为止，时间还在延续。"],
        ["perfect", "have visited", "正确。未结束时间段中的累计经历用现在完成时；主语 we 搭配 have。"],
        ["past-perfect", "had visited", "had visited 需要过去的观察点；这里统计的是截至现在的参观次数。"],
        ["continuous", "are visiting", "are visiting 表示当前正在参观或临时安排；句子统计的是三次已完成的经历。"],
      ],
    ),
    practiceQuestion(
      "present-perfect",
      3,
      "综合语境",
      "今天上午还没结束；打印机恢复工作，Sam 到现在已排除了三次卡纸。",
      "So far this morning, Sam ",
      " three paper jams, and the printer is working again.",
      "perfect",
      [
        ["past", "cleared", "cleared 可用于已结束的上午；so far this morning 把统计范围延伸到现在。"],
        ["continuous", "has been clearing", "has been clearing 强调排除卡纸的持续过程；句子给出的是已经完成的三次处理结果。"],
        ["perfect", "has cleared", "正确。到目前为止完成了三次，且上午仍在继续；Sam 是第三人称单数，用 has。"],
        ["past-perfect", "had cleared", "had cleared 需要另一个过去参照点；这里是今天到现在的累计结果。"],
      ],
    ),
  ],
  "present-perfect-continuous": [
    practiceQuestion(
      "present-perfect-continuous",
      1,
      "线索辨析",
      "现在仍在烤面包；Ravi 的手沾满面粉，活动从早上七点开始。",
      "Ravi's hands are covered in flour because he ",
      " bread since 7 a.m.",
      "perfect-continuous",
      [
        ["perfect", "has made", "has made 强调已经做好的面包或数量；语境突出从七点持续到现在的制作过程。"],
        ["continuous", "is making", "is making 描述现在正在做，但没有表达活动从早上七点已持续多久。"],
        ["perfect-continuous", "has been making", "正确。活动从过去开始且现在仍在进行；has been + -ing 强调过程和时长。"],
        ["past", "made", "made 把制作放在过去；这里活动从七点持续到现在，手上也仍有面粉。"],
      ],
    ),
    practiceQuestion(
      "present-perfect-continuous",
      2,
      "相近形式",
      "你的班次从六点开始，现在还没结束；你已经连续工作了三小时。",
      "You look exhausted. You ",
      " since six, and your shift is still going.",
      "perfect-continuous",
      [
        ["past", "worked", "worked 把工作放在过去；班次还在继续，所以需要连到现在。"],
        ["present-continuous", "are working", "are working 表示现在正在工作，但省略了从六点开始的持续时间。"],
        ["perfect", "have worked", "have worked 也能表示一段工作经历；这里特意强调连续进行的过程和疲惫原因。"],
        ["perfect-continuous", "have been working", "正确。have been working 从六点持续到现在，突出过程并解释现在的疲惫。"],
      ],
    ),
    practiceQuestion(
      "present-perfect-continuous",
      3,
      "综合语境",
      "雨到现在仍没有停；连续降雨已让草地和外套都湿透。",
      "The grass is soaked because it ",
      " continuously since noon, and it is still raining.",
      "perfect-continuous",
      [
        ["perfect", "has rained", "has rained 可概括降雨与现在的关系；连续进行且仍未停止时，语境聚焦过程和持续性。"],
        ["past", "rained", "rained 把降雨放在过去；句中明确说雨现在仍在下。"],
        ["perfect-continuous", "has been raining", "正确。since noon 给出起点，still raining 说明活动延续到现在；强调持续过程。"],
        ["present-continuous", "is raining", "is raining 说明现在在下雨，但没有呈现从中午开始持续的时间关系。"],
      ],
    ),
  ],
  "past-simple": [
    practiceQuestion(
      "past-simple",
      1,
      "线索辨析",
      "学校节目单记载了这场演出的具体日期；事件已经结束。",
      "I ",
      " my first piano recital on 14 May 2022.",
      "past",
      [
        ["past", "played", "正确。明确的已结束日期用一般过去时；play 的过去式是 played。"],
        ["continuous", "was playing", "was playing 会把动作呈现为过去某时正在进行；这里是日期明确的一次完整演出。"],
        ["perfect", "have played", "现在完成时通常不与明确结束的过去日期直接搭配。"],
        ["past-perfect", "had played", "had played 需要另一个过去参照点；这里只报告一次有具体日期的过去事件。"],
      ],
    ),
    practiceQuestion(
      "past-simple",
      2,
      "相近形式",
      "三个连续动作按顺序发生，句子讲完后离开这个场景。",
      "She ",
      " the door, picked up her bag, and left at eight.",
      "past",
      [
        ["past", "locked", "正确。lock、pick up、leave 构成按顺序发生的完整过去事件，用一般过去时平行叙述。"],
        ["continuous", "was locking", "was locking 会把锁门呈现为背景过程，与后面两个连续完成的动作不平行。"],
        ["perfect", "has locked", "has locked 将锁门结果连到现在；这里叙述的是昨晚八点已结束的一串动作。"],
        ["past-perfect", "had locked", "had locked 通常需要另一个过去参照点来突出更早发生；这里动作按顺序推进。"],
      ],
    ),
    practiceQuestion(
      "past-simple",
      3,
      "综合语境",
      "会议记录标明决策发生在上周二；现在只是回顾那次已结束的选择。",
      "At last Tuesday's meeting, the board ",
      " the proposal after a long discussion.",
      "past",
      [
        ["present", "approves", "approves 描述现在的事实或常规；last Tuesday 把决策放在已结束的过去。"],
        ["past", "approved", "正确。明确的过去会议中做出的决定用一般过去时；approve 加 -d。"],
        ["perfect", "has approved", "现在完成时通常不与 last Tuesday 这样的结束时间连用。"],
        ["past-continuous", "was approving", "was approving 强调当时正在批准的过程；语境给出的是讨论后作出的完整决定。"],
      ],
    ),
  ],
  "past-continuous": [
    practiceQuestion(
      "past-continuous",
      1,
      "线索辨析",
      "昨晚九点是观察时刻；文章还没写完，动作当时仍在进行。",
      "At nine last night, I ",
      " my essay; the final paragraph was unfinished.",
      "continuous",
      [
        ["continuous", "was writing", "正确。过去具体时刻的背景活动用 was + -ing；unfinished 说明写作当时仍在继续。"],
        ["simple", "wrote", "wrote 把写作作为完整事件；句子强调九点那一刻还没有写完。"],
        ["perfect", "had written", "had written 表示在过去参照点前已经写完；这里段落仍未完成。"],
        ["present-perfect-continuous", "have been writing", "have been writing 会把持续活动连到现在；句子的观察点是昨晚九点。"],
      ],
    ),
    practiceQuestion(
      "past-continuous",
      2,
      "相近形式",
      "停电这个短事件发生时，孩子们正在客厅看电影。",
      "The lights went out while the children ",
      " a film in the living room.",
      "continuous",
      [
        ["simple", "watched", "watched 会把看电影说成完整事件；while 后的活动是停电发生时的背景。"],
        ["continuous", "were watching", "正确。较长的背景活动用过去进行时；children 是复数，搭配 were。"],
        ["past-perfect", "had watched", "had watched 表示看电影先于停电结束；语境说停电时电影仍在播放。"],
        ["present", "are watching", "are watching 描述现在正在发生的事；停电和看电影都发生在过去。"],
      ],
    ),
    practiceQuestion(
      "past-continuous",
      3,
      "综合语境",
      "照片拍下来的瞬间，选手们还在冲过终点线的过程中。",
      "When the photo was taken, the runners ",
      " across the finish line.",
      "continuous",
      [
        ["continuous", "were crossing", "正确。照片对应过去的一个观察瞬间，选手们当时正处于冲线过程中。"],
        ["simple", "crossed", "crossed 把冲线作为完整事件；这里强调镜头拍下时动作尚在进行。"],
        ["past-perfect", "had crossed", "had crossed 表示在拍照前已经冲线；语境说明拍摄时仍在冲线。"],
        ["future", "will cross", "will cross 指向未来；句子描述已经拍下的过去瞬间。"],
      ],
    ),
  ],
  "past-perfect": [
    practiceQuestion(
      "past-perfect",
      1,
      "线索辨析",
      "叙述者特意突出布置椅子先完成，之后大门才打开。",
      "By the time the doors opened, volunteers ",
      " all the chairs in rows.",
      "past-perfect",
      [
        ["past-perfect", "had placed", "正确。大门打开是过去参照点；椅子更早已摆好，用 had + 过去分词清楚标出先后。"],
        ["past-simple", "placed", "一般过去时也能讲过去顺序；这里题目要突出开门前已经完成的较早动作。"],
        ["continuous", "were placing", "were placing 表示开门时还在摆椅子；语境说明椅子已全部摆好。"],
        ["present-perfect", "have placed", "have placed 将结果连到现在；句子中的两个参照点都在过去。"],
      ],
    ),
    practiceQuestion(
      "past-perfect",
      2,
      "相近形式",
      "Lila 到站时最后一班车已经开走；她看到电子牌显示“已发车”。",
      "When Lila reached the station, the last train ",
      ", so she called for a ride.",
      "past-perfect",
      [
        ["past", "left", "left 能叙述过去事件；had left 会更明确地将列车离站放在 Lila 到站之前。"],
        ["past-perfect", "had left", "正确。到站是过去参照点；列车已先离开，had left 把更早的事件标清楚。"],
        ["continuous", "was leaving", "was leaving 表示 Lila 到站时列车正在离开；电子牌说明列车已经发走。"],
        ["present-perfect", "has left", "has left 以现在为观察点；题目在叙述两个过去事件的先后。"],
      ],
    ),
    practiceQuestion(
      "past-perfect",
      3,
      "综合语境",
      "编辑是在作者修订完最后一段之后才检查文件；强调这个先后顺序。",
      "The editor checked the file only after the author ",
      " the final paragraph.",
      "past-perfect",
      [
        ["past-perfect", "had revised", "正确。检查文件是过去参照点，修订更早完成；only after 突出两个动作的先后。"],
        ["past", "revised", "revised 也可能用于顺序清楚的叙述；题目要求明确标出检查前已完成的修订。"],
        ["continuous", "was revising", "was revising 表示编辑检查时作者还在修改；only after 表示修订先完成。"],
        ["present-perfect", "has revised", "has revised 把修订连到现在；这里讨论的是两个过去动作之间的关系。"],
      ],
    ),
  ],
  "past-perfect-continuous": [
    practiceQuestion(
      "past-perfect-continuous",
      1,
      "线索辨析",
      "修理工找到漏油处之前，发动机已连续过热好几天；这解释了损坏原因。",
      "Before the mechanic found the leak, the engine ",
      " for several days.",
      "past-perfect-continuous",
      [
        ["past-perfect-continuous", "had been overheating", "正确。找到漏油处是过去参照点；发动机此前持续过热，for several days 强调时长和原因。"],
        ["past", "overheated", "overheated 叙述一次过去事件；语境要表达连续数日的过程。"],
        ["present-perfect-continuous", "has been overheating", "has been overheating 把过程连到现在；句子从修理工发现问题的过去时点回看。"],
        ["past-continuous", "was overheating", "was overheating 描述过去某时正在过热，但没有突出发现故障前已持续数日。"],
      ],
    ),
    practiceQuestion(
      "past-perfect-continuous",
      2,
      "相近形式",
      "哨声响起时，队员已跑了近一小时，所以明显疲惫。",
      "When the whistle blew, the players ",
      " for nearly an hour and looked exhausted.",
      "past-perfect-continuous",
      [
        ["past", "ran", "ran 可讲述一段过去活动；这里强调哨声响前已经持续近一小时。"],
        ["past-continuous", "were running", "were running 表示哨声响起时正在跑，但没有说明此前已跑了多长时间。"],
        ["past-perfect-continuous", "had been running", "正确。哨声响起是过去参照点；had been running 强调此前持续的训练过程。"],
        ["present-perfect", "have run", "have run 把跑步经历连到现在；句子中的哨声是过去的观察点。"],
      ],
    ),
    practiceQuestion(
      "past-perfect-continuous",
      3,
      "综合语境",
      "火警响起前有人一直在煎洋葱很久；厨房里的烟味仍解释着警报原因。",
      "The kitchen smelled of smoke because someone ",
      " onions for too long before the alarm went off.",
      "past-perfect-continuous",
      [
        ["past-perfect", "had fried", "had fried 强调动作已完成；语境更突出煎了很久这一持续过程和它造成的烟味。"],
        ["past-perfect-continuous", "had been frying", "正确。警报响起是过去参照点；此前长时间持续煎洋葱解释了烟味。"],
        ["past", "fried", "fried 可讲一次过去的煎制事件；这里要说明过程持续太久并造成结果。"],
        ["past-continuous", "was frying", "was frying 描述警报响起时正在煎；语境聚焦警报前已经持续很久的原因。"],
      ],
    ),
  ],
  "future-simple": [
    practiceQuestion(
      "future-simple",
      1,
      "线索辨析",
      "说话人刚知道对方需要搭车，现在当场主动提出帮忙。",
      "I didn't know you needed a lift. I ",
      " you home.",
      "will",
      [
        ["will", "will drive", "正确。听到需求后当场作出的决定或主动帮助，常用 will 表达。"],
        ["continuous", "am driving", "am driving 更像已经安排好的行程；这里的决定刚刚作出。"],
        ["past", "drove", "drove 表示已经完成的过去搭车；说话人现在才提出要送。"],
        ["past-perfect", "had driven", "had driven 需要另一个过去参照点；这里是当下对未来的提议。"],
      ],
    ),
    practiceQuestion(
      "future-simple",
      2,
      "相近形式",
      "说话人表达自己的判断；没有看到具体证据，只是在预测新图书馆受欢迎。",
      "I think the new library ",
      " more students once the study rooms open.",
      "will",
      [
        ["will", "will attract", "正确。I think 引出个人预测；主语 the new library 后用 will + 动词原形。"],
        ["continuous", "is attracting", "is attracting 描述现在正在吸引学生；这里预测的是开放之后的情况。"],
        ["past", "attracted", "attracted 把吸引学生放在过去；study rooms 还没有开放。"],
        ["perfect", "has attracted", "has attracted 表示到现在已吸引了学生；此处预测的是之后的反应。"],
      ],
    ),
    practiceQuestion(
      "future-simple",
      3,
      "综合语境",
      "Jo 向同伴作出长期承诺：以后即使别人索要，也不会把对方的笔记给别人看。",
      "Your notes are safe. I promise I ",
      " them to anyone, even if they ask me to.",
      "will",
      [
        ["will", "won't show", "正确。明确承诺常用 will；否定形式 won't 表示答应不做某事。"],
        ["continuous", "am not showing", "am not showing 更像当前安排；这里说话人承诺今后即使别人索要也不会展示。"],
        ["past", "didn't show", "didn't show 只报告过去没有展示；承诺还约束未来行为。"],
        ["perfect", "haven't shown", "haven't shown 表示到现在为止没有给别人看，不表达未来承诺。"],
      ],
    ),
  ],
  "future-continuous": [
    practiceQuestion(
      "future-continuous",
      1,
      "线索辨析",
      "演出日程已经确定；晚上八点是演出进行中的一个时刻。",
      "At eight tonight, the orchestra ",
      " the second half of the concert.",
      "future-continuous",
      [
        ["future-continuous", "will be performing", "正确。晚上八点是未来观察时刻，演出届时正在进行，用 will be + -ing。"],
        ["future-simple", "will perform", "will perform 可以说未来会演出，但没有把动作定位为八点正在进行。"],
        ["present", "performs", "performs 可描述固定日程；这里问的是八点演出进行到什么阶段。"],
        ["future-perfect", "will have performed", "will have performed 表示到八点前已经演完；日程说明届时才在演奏第二部分。"],
      ],
    ),
    practiceQuestion(
      "future-continuous",
      2,
      "相近形式",
      "航班时刻已定；下周一此时，飞机仍在太平洋上空。",
      "This time next Monday, I ",
      " over the Pacific, so I won't have internet.",
      "future-continuous",
      [
        ["future-simple", "will fly", "will fly 只说明将来飞行；此处强调下周一这个时刻旅程仍在进行。"],
        ["future-continuous", "will be flying", "正确。this time next Monday 提供未来观察点，飞行届时正在进行。"],
        ["future-perfect", "will have flown", "will have flown 表示到那时飞行已结束；语境说那时还在太平洋上空。"],
        ["past", "flew", "flew 把旅程放在过去；句子明确指向下周一。"],
      ],
    ),
    practiceQuestion(
      "future-continuous",
      3,
      "综合语境",
      "节目单显示颁奖礼九点开始；十点时主持人仍会在台上介绍获奖者。",
      "At ten, the host ",
      " the final award, according to the programme.",
      "future-continuous",
      [
        ["future-continuous", "will be presenting", "正确。节目流程把十点设为未来观察点；介绍活动届时仍在进行。"],
        ["future-simple", "will present", "will present 说明将来会介绍，但没有凸显十点时正在进行这一画面。"],
        ["future-perfect", "will have presented", "will have presented 会表示十点前已经介绍完；节目安排说十点正在介绍。"],
        ["present-continuous", "is presenting", "is presenting 通常从现在谈已安排的活动；句子需要描写未来某一时刻的进行状态。"],
      ],
    ),
  ],
  "future-perfect": [
    practiceQuestion(
      "future-perfect",
      1,
      "线索辨析",
      "团队预计六月底前桥梁就会建完；道路要到八月才开放。",
      "The crew expects that they ",
      " the bridge by the end of June.",
      "future-perfect",
      [
        ["future-perfect", "will have finished", "正确。六月底是未来参照点；will have finished 表示到那时桥梁已经完工。"],
        ["future-simple", "will finish", "will finish 说明将来会完工；完成时更明确表达六月底之前已完成。"],
        ["future-continuous", "will be finishing", "will be finishing 表示六月底可能仍在收尾；语境预计届时已经完工。"],
        ["present-perfect", "have finished", "have finished 把完成连到现在；这里的截止时间在未来。"],
      ],
    ),
    practiceQuestion(
      "future-perfect",
      2,
      "相近形式",
      "请强调等你回家时，杂货已经收拾好，厨房也会空出来。",
      "By the time you get home, I ",
      " the groceries away.",
      "future-perfect",
      [
        ["future-simple", "will put", "will put 表达将会收拾，但没有把回家这一时点上的完成结果说清楚。"],
        ["future-perfect", "will have put", "正确。到你回家这一未来时点，杂货预计已经收好；use will have + 过去分词。"],
        ["future-continuous", "will be putting", "will be putting 表示回家时可能还在收拾；题意要求届时已经完成。"],
        ["past-perfect", "had put", "had put 以过去时点为参照；这里的回家时间在将来。"],
      ],
    ),
    practiceQuestion(
      "future-perfect",
      3,
      "综合语境",
      "支持团队在统计今天的请求；到午夜前，所有请求都要处理完成。",
      "By midnight, the support team ",
      " every request received today.",
      "future-perfect",
      [
        ["future-perfect", "will have answered", "正确。午夜是未来截止点；此时今天收到的请求预计都已答复。"],
        ["future-simple", "will answer", "will answer 只承诺未来答复；题意关注到午夜时已完成的总量。"],
        ["future-continuous", "will be answering", "will be answering 表示午夜时还在答复；语境要求到那时全部完成。"],
        ["present-perfect", "have answered", "have answered 从现在总结已完成的工作；by midnight 把参照点放在未来。"],
      ],
    ),
  ],
  "future-perfect-continuous": [
    practiceQuestion(
      "future-perfect-continuous",
      1,
      "线索辨析",
      "八月时我仍打算留在公司；句子突出届时累计的工作年限。",
      "By August, I ",
      " at this company for ten years, and I plan to stay.",
      "future-perfect-continuous",
      [
        ["future-perfect-continuous", "will have been working", "正确。到八月时工作已持续十年且仍继续；强调未来参照点前累计的过程时长。"],
        ["future-simple", "will work", "will work 只说未来会工作；没有表达截至八月已经持续十年的时长。"],
        ["future-perfect", "will have worked", "will have worked 也可概括任职年限；此处 plan to stay 强调届时仍继续的过程。"],
        ["present-perfect-continuous", "have been working", "have been working 把时长连到现在；题目计算的是到未来八月时的十年。"],
      ],
    ),
    practiceQuestion(
      "future-perfect-continuous",
      2,
      "相近形式",
      "道路维修下午仍会继续；到四点时，施工队已经连续施工六小时。",
      "At four p.m., the crew ",
      " the road for six hours, so traffic may still be slow.",
      "future-perfect-continuous",
      [
        ["future-continuous", "will be repairing", "will be repairing 说明四点正在施工；句子还要求表达此前已持续六小时。"],
        ["future-perfect-continuous", "will have been repairing", "正确。四点是未来参照点，for six hours 计算到那时已持续的施工时长。"],
        ["future-perfect", "will have repaired", "will have repaired 更突出到四点前已完成的修路结果；语境说施工届时仍在继续。"],
        ["past-perfect-continuous", "had been repairing", "had been repairing 以过去时点为参照；句子把观察点放在未来四点。"],
      ],
    ),
    practiceQuestion(
      "future-perfect-continuous",
      3,
      "综合语境",
      "赛季结束时 Sofia 已连续每周末参赛五个月，之后仍剩两场比赛。",
      "By the end of the season, Sofia ",
      " every weekend for five months, with two matches still to play.",
      "future-perfect-continuous",
      [
        ["future-simple", "will compete", "will compete 说她将来会参赛；没有表达赛季结束时累计的五个月。"],
        ["future-perfect", "will have competed", "will have competed 可以总结已经完成的比赛经历；这里还要突出持续的频率与时长。"],
        ["present-perfect-continuous", "has been competing", "has been competing 把过程连到现在；句子以赛季结束这个未来时点累计时长。"],
        ["future-perfect-continuous", "will have been competing", "正确。到赛季结束时该活动已持续五个月，而且比赛还没结束，强调持续过程。"],
      ],
    ),
  ],
  "future-in-past-simple": [
    practiceQuestion(
      "future-in-past-simple",
      1,
      "线索辨析",
      "中午 Mark 说的是下班后的电话；电话安排在他说话之后。",
      "At noon, Mark said he ",
      " us after work.",
      "would",
      [
        ["would", "would call", "正确。said 是过去参照点；after work 的电话在那个时点之后，用 would 表示过去视角的未来。"],
        ["will", "will call", "will 从现在视角指向未来；句子转述的是 Mark 当时说的后续安排。"],
        ["past-perfect", "had called", "had called 表示电话早于中午已经打出；语境说电话安排在下班后。"],
        ["would-perfect", "would have called", "would have called 会表示到另一较晚时点前已完成；句子只报告一个后续动作。"],
      ],
    ),
    practiceQuestion(
      "future-in-past-simple",
      2,
      "相近形式",
      "Ella 在日记中写下次月搬家的打算，当时还不知道具体日期。",
      "Ella wrote that she ",
      " the following month, though she did not know the exact date.",
      "would",
      [
        ["past", "moved", "moved 把搬家说成已经发生；日记写下的计划在当时之后。"],
        ["past-perfect", "had moved", "had moved 表示搬家早于写日记的过去时点；语境说计划尚未发生。"],
        ["would", "would move", "正确。wrote 提供过去参照点；the following month 表示之后预期发生的搬家。"],
        ["would-perfect", "would have moved", "would have moved 需要更晚的参照期限来强调届时已完成；句子只说之后计划搬家。"],
      ],
    ),
    practiceQuestion(
      "future-in-past-simple",
      3,
      "综合语境",
      "早餐时的天气预报预测风暴会在当天晚些时候结束。",
      "At breakfast, the forecast predicted the storm ",
      " before evening.",
      "would",
      [
        ["would", "would end", "正确。早餐时是过去预报的参照点；风暴预计在之后、傍晚前结束。"],
        ["will", "will end", "will 从现在角度预测；句子报告的是早餐时做出的预测。"],
        ["past-perfect", "had ended", "had ended 表示风暴在早餐前已经结束；预测内容指向之后。"],
        ["would-perfect", "would have ended", "would have ended 会从过去看向更晚的截止点并强调届时已完成；这里表达的是一般预测。"],
      ],
    ),
  ],
  "future-in-past-continuous": [
    practiceQuestion(
      "future-in-past-continuous",
      1,
      "线索辨析",
      "周二 Jo 说到次日六点时，她会仍在去布里斯托的火车上。",
      "On Tuesday, Jo said that at six the next evening she ",
      " on the train to Bristol.",
      "would-continuous",
      [
        ["would-continuous", "would still be travelling", "正确。周二是过去参照点；次日六点在之后，still be travelling 强调届时仍在旅途中。"],
        ["would", "would travel", "would travel 说明之后会出行，但不表示六点时旅程仍在进行。"],
        ["past-perfect", "had travelled", "had travelled 表示旅行早于周二；句子说的是周二之后的次日六点。"],
        ["will-continuous", "will be travelling", "will be travelling 从现在角度描述未来；转述过去的说法时题目要求 past viewpoint。"],
      ],
    ),
    practiceQuestion(
      "future-in-past-continuous",
      2,
      "相近形式",
      "午餐时 Ben 说明晚九点他会在家看决赛，而不是在公司工作。",
      "At lunch, Ben explained that at nine he ",
      " the final at home.",
      "would-continuous",
      [
        ["past", "watched", "watched 把看决赛放在已经发生的过去；午餐时谈的是当晚的计划。"],
        ["would-continuous", "would be watching", "正确。午餐时是过去参照点，晚九点在之后；届时的观看活动预计正在进行。"],
        ["would-perfect", "would have watched", "would have watched 表示到九点前已经看完；这里说九点时正在观看。"],
        ["past-continuous", "was watching", "was watching 把观看放在午餐前后的过去；这里的九点还没到。"],
      ],
    ),
    practiceQuestion(
      "future-in-past-continuous",
      3,
      "综合语境",
      "救援队在前一天就已出发；预计黎明时仍在穿越山谷。",
      "We knew that at dawn the rescue team ",
      " through the valley.",
      "would-continuous",
      [
        ["would-continuous", "would be moving", "正确。knew 是过去参照点；at dawn 指向之后，be moving 描述届时正在进行的行动。"],
        ["would", "would move", "would move 表示之后会移动，但没有把黎明这个时刻的行动呈现为进行中。"],
        ["past-perfect", "had moved", "had moved 表示移动发生在 knew 之前；黎明时的行动还在未来。"],
        ["will-continuous", "will be moving", "will be moving 以现在为参照点；句子通过 knew 转述过去的预测。"],
      ],
    ),
  ],
  "future-in-past-perfect": [
    practiceQuestion(
      "future-in-past-perfect",
      1,
      "线索辨析",
      "周一实验室预计结果会在周四评审之前到齐；现在从周一的视角转述。",
      "On Monday, the lab expected the results ",
      " before Thursday's review.",
      "would-perfect",
      [
        ["would-perfect", "would have arrived", "正确。周一是过去预期点，周四在之后；到评审前预计结果已经到齐。"],
        ["past-perfect", "had arrived", "had arrived 表示结果早于周一已经到达；题意是预计它们之后才会到。"],
        ["would", "would arrive", "would arrive 表示之后会到；would have arrived 更明确表达在周四之前已完成。"],
        ["future-perfect", "will have arrived", "will have arrived 从现在的未来视角描述完成；句子报告周一做出的预期。"],
      ],
    ),
    practiceQuestion(
      "future-in-past-perfect",
      2,
      "相近形式",
      "早餐时爸爸相信客人中午到之前，他会把围栏刷完。",
      "At breakfast, Dad was confident he ",
      " the fence before the guests arrived at noon.",
      "would-perfect",
      [
        ["would-perfect", "would have painted", "正确。早餐是过去预期点；客人中午到达在后，粉刷预计届时已完成。"],
        ["past", "painted", "painted 讲已发生的过去事件；语境是早餐时对中午前完成情况的预期。"],
        ["would-continuous", "would be painting", "would be painting 表示客人到时可能还在粉刷；题目强调那之前已经刷完。"],
        ["past-perfect", "had painted", "had painted 表示早餐前已经刷好；预期的完成时间在早餐之后。"],
      ],
    ),
    practiceQuestion(
      "future-in-past-perfect",
      3,
      "综合语境",
      "周五前记者相信编辑已经批准文章，所以计划届时庆祝。",
      "The reporter thought the editor ",
      " the article by Friday, so she planned to celebrate.",
      "would-perfect",
      [
        ["would-perfect", "would have approved", "正确。thought 是过去预期点；by Friday 是更晚的期限，表示届时预计已批准。"],
        ["past-perfect", "had approved", "had approved 会把批准放在 thought 之前；by Friday 指向当时之后的期限。"],
        ["would", "would approve", "would approve 表示之后会批准；完成时更清楚表达周五前已完成。"],
        ["will-perfect", "will have approved", "will have approved 从现在看向未来期限；句子转述的是记者过去的判断。"],
      ],
    ),
  ],
  "future-in-past-perfect-continuous": [
    practiceQuestion(
      "future-in-past-perfect-continuous",
      1,
      "线索辨析",
      "三月时 Leila 预计到九月她已在加拿大住满半年，而且之后没有搬家的打算。",
      "In March, Leila thought that by September she ",
      " in Canada for six months.",
      "would-perfect-continuous",
      [
        ["would-perfect-continuous", "would have been living", "正确。三月是过去参照点，九月在后；结构强调截至那时已持续半年的居住状态。"],
        ["would-perfect", "would have lived", "would have lived 可概括住过多久；这里预期居住仍会继续，重点在持续过程。"],
        ["past-perfect-continuous", "had been living", "had been living 把居住放在三月之前；题目计算的是到三月之后九月时的时长。"],
        ["future-perfect-continuous", "will have been living", "will have been living 以现在为过去时点之后的未来参照；句子明确转述三月的想法。"],
      ],
    ),
    practiceQuestion(
      "future-in-past-perfect-continuous",
      2,
      "相近形式",
      "教练在七月预测决赛时球队已一起训练十二周，且训练之后还会继续。",
      "In July, the coach predicted that by the final the team ",
      " together for twelve weeks.",
      "would-perfect-continuous",
      [
        ["would-perfect-continuous", "would have been training", "正确。七月是过去预测点，决赛在后；by then 与持续十二周突出届时已延续的训练过程。"],
        ["would-perfect", "would have trained", "would have trained 可把训练量概括为结果；上下文说训练到决赛时还会继续。"],
        ["past-perfect-continuous", "had been training", "had been training 指向七月以前的训练；句子预估的是之后到决赛时的时长。"],
        ["future-perfect-continuous", "will have been training", "will have been training 从现在看向未来；题目报告教练在七月作出的预测。"],
      ],
    ),
    practiceQuestion(
      "future-in-past-perfect-continuous",
      3,
      "综合语境",
      "三月的工程报告预计到十二月桥梁已施工三年；工程预计还会持续到来年春天。",
      "The engineers expected that by December the crew ",
      " on the bridge for three years.",
      "would-perfect-continuous",
      [
        ["would-perfect-continuous", "would have been working", "正确。expected 是过去参照点；到十二月工程已持续三年且未结束，突出累计时长和过程。"],
        ["would-perfect", "would have worked", "would have worked 更像总结届时完成的工作；工程还在继续，重点是持续过程。"],
        ["past-perfect-continuous", "had been working", "had been working 把施工时长计算到过去参照点之前；十二月在 expected 之后。"],
        ["future-perfect-continuous", "will have been working", "will have been working 以现在作预测起点；本句回顾的是工程师过去的预期。"],
      ],
    ),
  ],
}
